Upgrade to Rails 7.0
bebraven/platform pull request #1090
Opened 2022-05-26 20:07 UTC by sadleb

# Description
Upgrade to Rails 7.0. Overview of major changes from 6.1 -> 7.0 here: https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0

Task: https://app.asana.com/0/1201131148207877/1200066294473271

Note that Rails 7.0 has made some drastic changes to its default approach to handling Javascript. However, it still works with the old ways too. That is a whole project unto itself, so I'm **not** making any changes to the JS pipeline and tools in this PR. Follow-up tasks:
* Upgrade Webpacker: https://app.asana.com/0/1201131148207877/1200066294473247
* Upgrade React: https://app.asana.com/0/1201131148207877/1200066294473253

# Deployment
* [x] Generate the following three ENV vars using [this guide](https://edgeguides.rubyonrails.org/active_record_encryption.html) and setting them in prod **BEFORE** deploy.
* `ENV['ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY']`
* `ENV['ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY']`
* `ENV['ACTIVE_RECORD_ENCRYPTION_DERIVATION_SALT']`

# Testing
* [x] specs are passing
* [x] sanity checked some stuff like Modules and Projects
* [x] made sure the React submit button on projects works
* [x] sanity checked that Honeycomb and trace propagation from Boomerang JS spans still works
* [x] sanity checked publishing a new Rise360 module
* [x] sanity checked Content Editor
* [x] sanity checked that the recurring unique jobs sidekiq scheduler works
* [x] sanity checked syncing something from SF to Canvas

# Screenshots

Example of new specs Honeycomb traces
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/5596986/171671052-d1e90ba8-9c6d-49a2-a977-a47c1b7e39ae.png">

2022-05-26 20:09 UTC, sadleb commented on config/secrets.yml
> +  active_record_encryption_derivation_salt: <%= ENV['ACTIVE_RECORD_ENCRYPTION_DERIVATION_SALT'] %>
TODO: generate some of these using [the guide](https://edgeguides.rubyonrails.org/active_record_encryption.html) and set prod specific ones.

2022-05-27 21:26 UTC, sadleb commented on Gemfile
> -  gem 'spring-watcher-listen', '~> 2.0.0'
Spring and Bootsnap weren't playing nice together. Was getting this error:
`You have already activated digest 3.0.0, but your Gemfile requires digest 3.1.0.`

[See here](https://aboobacker.in/2021/06/28/bootsnap-and-spring-understanding-rails-boottime-optimisations.html) for any overview of what these gems are/do.

Rails 7 no longer ships with Spring enabled by default and the `spring-watcher-listen` gem doesn't seem to be
maintained anymore and doesn't support v3 or v4 of Spring.

So I just removed it and tried things out. Error goes away. No noticeable difference from some quick sanity testing of Guard reloading changes or rake tasks running.

2022-05-27 21:29 UTC, sadleb commented on app/controllers/cas_controller.rb
> +          redirect_to Utils.build_ticketed_url(@service, st), allow_other_host: true and return
See the comment in `spec/rails_helper.rb` for what's going on here.

2022-05-27 21:31 UTC, sadleb commented on Gemfile
> -
See notes and links in `db/migrate/20220526120958_change_keypairs_to_active_record_encryption.rb` for more info

2022-06-02 15:50 UTC, sadleb commented on spec/spec_helper.rb
> +    Excon.defaults[:allow_unstubbed_requests] = true
Source code here that led to the error: https://github.com/excon/excon/blob/master/lib/excon/middlewares/mock.rb#L52

2022-06-03 16:05 UTC, sadleb commented on spec/spec_helper.rb
>    end
See the screenshot in the description for what this results in.

2022-06-03 16:58 UTC, sadleb commented on spec/spec_helper.rb
> +    @root_honeycomb_span.send
See the screenshot in the description for what this results in.

2022-06-06 15:54 UTC, elenabaurkot reviewed
Lgtm 👍

2022-06-06 15:54 UTC, elenabaurkot commented on db/schema.rb
> +    t.datetime "created_on", precision: nil, null: false
Does specifying `precision: nil` mean it won't have any decimals?

2022-06-06 17:52 UTC, sadleb commented on db/schema.rb
> +    t.datetime "created_on", precision: nil, null: false
Looks like it just means "use the database default for that type" https://github.com/rails/rails/issues/44571#issuecomment-1054758649

2022-06-06 20:43 UTC, rshipp commented on app/controllers/cas_controller.rb
> +          redirect_to Utils.build_ticketed_url(@service, st), allow_other_host: true and return
can you explain this more? turning off this security feature just to get the tests to pass seems suboptimal

2022-06-06 20:45 UTC, rshipp commented on config/secrets.yml
> +  active_record_encryption_derivation_salt: <%= ENV['ACTIVE_RECORD_ENCRYPTION_DERIVATION_SALT'] %>
if you're making this assertion, we need to never copy production data into staging/local like we've done in the past

2022-06-06 20:47 UTC, rshipp commented on db/schema.rb
> +    t.datetime "graded_at", precision: nil
the fact that anything that previously had no precision now has `precision: nil`, while anything that had `precision: 6` now has no precision, makes me worry this is going to end up in a different state the next time somebody runs a migration or something

2022-06-06 20:48 UTC, rshipp requested changes
adding the security bypass to all the redirects is not safe, we should try to find other options to get the tests to pass

2022-06-08 15:19 UTC, sadleb commented on app/controllers/cas_controller.rb
> +          redirect_to Utils.build_ticketed_url(@service, st), allow_other_host: true and return
Here is a little [article](https://blog.saeloun.com/2022/02/08/rails-7-raise-unsafe-redirect-error) with some links to the source code. We have to do it b/c we redirect from `platform.braven.org` to `braven.instructure.com`. It's not just for specs. It's just new behavior. The default used to be `true` for all redirects but now it's false, so I had to go through the redirects that went to Canvas and explicitly allow them

2022-06-08 15:25 UTC, sadleb commented
> adding the security bypass to all the redirects is not safe, we should try to find other options to get the tests to pass

It's not all redirects. That was the old behavior. See my response [here](https://github.com/bebraven/platform/pull/1090#discussion_r892521600).

2022-06-08 15:34 UTC, sadleb commented on db/schema.rb
> +    t.datetime "graded_at", precision: nil
This whole thing is confusing to me, but reading through the change and specifically [this comment ](https://github.com/rails/rails/issues/44571#issuecomment-1056131789) makes me think it won't keep switching around in future migrations. It's a separate question whether we want to go back and be consistent or not. Outside the scope of this PR though.

2022-06-13 15:24 UTC, rshipp commented on app/controllers/cas_controller.rb
> +          redirect_to Utils.build_ticketed_url(@service, st), allow_other_host: true and return
can you verify which redirects *must* allow other domains? looking at this briefly, i can see this one https://github.com/bebraven/platform/pull/1090/files#diff-1cc94f8305c6c7787c0b817518c0b004af88947cf2b6fa6a8363c1f14a455890R117 at least does not and should not allow that behavior. we had to do a bunch of manual work on the URL to make sure it didn't point to other hosts, in fact.

2022-06-13 20:13 UTC, sadleb commented on app/controllers/lti_launch_controller.rb
> +    redirect_to "#{LTI_AUTH_RESPONSE_URL}?#{@lti_launch.auth_params.to_query}", allow_other_host: true
This is `https://canvas.instructure.com/api/lti/authorize_redirect`

2022-06-13 20:15 UTC, sadleb commented on app/controllers/cas_controller.rb
> +          redirect_to Utils.build_ticketed_url(@service, st), allow_other_host: true and return
Good call on that one. That was a mistake. I removed it and fixed the specs. The rest in this file are to the `service` param which is generally Canvas (but can be platform in some cases), so they need `allow_other_host`. Will double check the rest.

2022-06-13 20:39 UTC, rshipp approved these changes

2022-06-14 15:51 UTC, merged

2022-06-15 13:27 UTC, sadleb commented
Note that when I tried to deploy to heroku using `git push heroku main` it failed with this:
```
remote:        error Command "webpack" not found.
remote:        
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
```
[This article](https://discuss.rubyonrails.org/t/deploying-to-heroku-command-webpack-not-found/76409) helped me solve it by adding the nodejs buildpack:
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/5596986/173838596-aa4f98f6-44f8-4c15-90e3-edaabf84cd18.png">