Set reminder to re-do Zoom calls after a rate limit error
bebraven/platform pull request #1156
Opened 2022-09-07 17:05 UTC by tomlovett

# Description
If we send too many requests to the Zoom API, set reminder to try again on the next sync after the rate limit has expired. (Zoom's rate limit expires on the next UTC day.)

(Additional formatting changes added per RuboCop.)

# Motivation and Context
There were Zoom meetings with outdated information for the participants. Tracing back what happened, updates to those meetings were being rejected because we had exceeded Zoom's rate limit of changes for the same email/meeting pair. 

Task: https://app.asana.com/0/1201131148207877/1202895413804903

2022-09-08 16:24 UTC, elenabaurkot commented on app/services/sync_zoom_links_for_participant.rb
> +      @participant_sync_info.sfid, { 'Zoom_Rate_Limit_Until__c' => midnight_in_user_timezone }
This all looks good to me here as long as some manual testing has been done to make sure time zones are actually being set correctly here 👍

2022-09-08 16:47 UTC, tomlovett commented on app/services/sync_zoom_links_for_participant.rb
> +      @participant_sync_info.sfid, { 'Zoom_Rate_Limit_Until__c' => midnight_in_user_timezone }
I did not manually check this, so I'm going back over it now. Good catch!

2022-09-08 22:41 UTC, elenabaurkot commented on app/services/sync_zoom_links_for_participant.rb
> +      @participant_sync_info.sfid, { 'Zoom_Rate_Limit_Until__c' => midnight_in_user_timezone }
Time zones always trip me up (I tend to reverse them haha)

2022-09-08 23:20 UTC, elenabaurkot requested changes

2022-09-08 23:20 UTC, elenabaurkot commented on app/services/sync_zoom_links_for_participant.rb
> +    midnight_after_next = DateTime.now.in_time_zone(user_timezone).end_of_day + 1.days
If the current date / time is September 8 at 7:13pm, I think the time we want to get is September 9 at the very start of the day 12:00am - I think this would end up getting us September 9 at 11:59pm, so the very end of the day. I'm thinking we could do something like `DateTime.now.in_time_zone(user_timezone).beginning_of_day + 1.day` (which I think would get us 12:00 am Sept 9) or `DateTime.now.in_time_zone(user_timezone).end_of_day + 1.minute` (which would get us 12:01 am on Sept 9). Otherwise I think we would be waiting over 24 hours before retrying the Zoom API request. I'm not sure if this would change what we want to name the variable or if that would still make sense.

2022-09-09 13:58 UTC, elenabaurkot requested changes

2022-09-09 13:58 UTC, elenabaurkot commented on app/services/sync_salesforce_participant.rb
> -    return if !@participant_sync_info.has_canvas_staff_permissions?
The only reason I can think of to leave it this way is so that we don't have to go through the other logic if the person doesn't have staff permissions we can just exit the function. I'm not sure whether the time saving there makes much of a difference or not or if it just seems cleaner to write it the other way @tomlovett?

2022-09-09 13:58 UTC, elenabaurkot commented on app/services/sync_salesforce_participant.rb
> +    else
I'm not positive, but I think we may need to check the above conditions specifically because we only want to raise this ArgumentError in the instance where the cohort schedule and cohort section are both nil - otherwise I think there could be scenarios where all of the conditions above this don't evaluate to true and this will automatically raise even if they do have a cohort schedule / section

2022-09-09 13:58 UTC, elenabaurkot commented on app/services/sync_salesforce_participant.rb
> +    if @participant_sync_info.contact_changed?
I think I'm a little confused about this part, it might be more easily explained in a call - the way I am reading the original code is we want to return if `@participant_sync_info.contact_changed?` and not SyncSalesforceContact, but here it looks like the opposite. I don't know whether we want this change or not, but I think I am having a little trouble fully comprehending what the original code is doing here and maybe this is what we want

2022-09-09 14:01 UTC, tomlovett commented on app/services/sync_salesforce_participant.rb
> +    if @participant_sync_info.contact_changed?
These were all local refactoring that I was messing around with, but didn't mean to commit. It's been taken out 😅

2022-09-09 14:03 UTC, elenabaurkot commented on app/services/sync_zoom_links_for_participant.rb
> +    midnight_after_next = DateTime.now.in_time_zone(user_timezone).end_of_day + 1.days
Ah good call, did not think about that, I think originally I was getting the next day in utc and then converting time zones, but I think this update makes more sense 👍

2022-09-09 14:03 UTC, elenabaurkot commented on app/services/sync_salesforce_participant.rb
> +    if @participant_sync_info.contact_changed?
Ah okay haha disregard

2022-09-09 14:05 UTC, elenabaurkot approved these changes
This all looks good to me!

2022-09-09 14:07 UTC, merged

2022-09-10 05:22 UTC, sadleb commented on app/services/sync_zoom_links_for_participant.rb
> +      # Do not remove the rate-limit flag here, because we still need it for zoom_meeting_2
janky tech debt ftw

2022-09-10 05:23 UTC, sadleb commented on app/services/sync_zoom_links_for_participant.rb
> +      # This is janky TECH DEBT; shoould fix when combining both links into the same flow
Janky tech debt ftw

2022-09-10 05:28 UTC, sadleb commented on spec/models/participant_sync_info_spec.rb
> +      let(:participant) { build :participant_sync_info, cohort: nil }
All these whitespace changes are making me think. I was just raw dogging this stuff in Vim. But with a bunch of people working on the same files, a standard vscode (or some other IDE) setup feels important.

2022-09-12 13:01 UTC, tomlovett commented on spec/models/participant_sync_info_spec.rb
> +      let(:participant) { build :participant_sync_info, cohort: nil }
Yup Brian! We've started using RuboCop to standardize our formatting. It'll take a while before we clean up the entire codebase, but we'll get there little-by-little!