Prevent sync alert for missing LC course for staff onboarding program
bebraven/platform pull request #1224
Opened 2022-12-09 15:09 UTC by elenabaurkot

# Description
We recently launched a staff onboarding program specifically for staff to onboard, which only needed an Canvas Accelerator course and no LC Playbook. We temporarily added code in the PR [Launch Staff onboarding course with no LC Playbook](https://github.com/bebraven/platform/pull/1215) that let us launch the Staff onboarding course without an LC Playbook. The code was reverted after launching since we do always want an LC Playbook when launching our standard courses, but since this was a one-time non standard course we didn't want to keep the code in there. 

The Salesforce sync that runs every five minutes to sync changes for current and future courses, checks that each program being synced has an Accelerator course and an LC Playbook course linked to the program. After launching this course we were receiving alerts that the staff onboarding program was missing the LC Playbook course. This update prevents alerting for a missing LC Playbook course only for the staff onboarding program since it shouldn't have one. 

# Motivation and Context
We don't need an LC Playbook for the staff onboarding course, so we don't need an alert the LC Playbook course is missing. 

Task: https://app.asana.com/0/1201131148207877/1203511615467171/f

2022-12-09 18:42 UTC, ThotsaphonB requested changes
2 issues

2022-12-09 18:42 UTC, ThotsaphonB commented on app/services/sync_salesforce_program.rb
> +      staff_onboarding_program_sfid = 'a2Y5c000001UOsxEAG'
Move staff_onboarding_program_sfid to the Salesforce Constants file

2022-12-09 18:42 UTC, ThotsaphonB commented on app/services/sync_salesforce_program.rb
> +      ZoomAPI::ZoomMeetingDoesNotExistError, ZoomAPI::TooManyRequestsError,
Separate into 2 lines

2022-12-12 14:11 UTC, tomlovett approved these changes
LGTM after Ben's notes.

Thanks for writing tests to handle this new behavior!

2022-12-12 14:39 UTC, merged