Grading rake task
bebraven/platform pull request #334
Opened 2020-08-27 20:20 UTC by rshipp

[wip]

2020-08-27 20:47 UTC, jessouyangbraven commented on lib/tasks/grade_lessons.rake
> +        grades[record.canvas_course_id][canvas_assignment_id][record.user.canvas_id] = LessonGradeCalculator.compute_grades(record.user, record.root_activity_id)
`compute_grade` singular in PR #333.

2020-08-27 20:51 UTC, jessouyangbraven commented on lib/tasks/grade_lessons.rake
> +    }
I'm not sure what `uniq` does. Are we going to get the most recent record for each quiz question when we dedupe? 

There's logic in `LessonGradeCalculator` to do this get the most recent record for each quiz question, so this might be unnecessary?

2020-08-27 20:55 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +    }
this was just to take the list from 

```
user1, http://activity1/quiz1/question1
user1, http://activity1/quiz1/question2
user1, http://activity1/quiz2/question1
```

to 

```
user1, http://activity1
```

Otherwise, we'd run `compute_grades` once for each quiz question plus once for the overall lesson, when we only want to run it once.

2020-08-27 20:56 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +    }
This is where I was reading about `uniq` https://www.rubyguides.com/2019/08/ruby-uniq-method/

2020-08-27 21:02 UTC, jessouyangbraven commented on lib/tasks/grade_lessons.rake
> +          CanvasAPI.update_lesson_grades(canvas_course_id, canvas_assignment_id, grades_by_user_id)
This hash needs to be keyed on canvas user ID. Am I just missing it in the code? 

I can add code to `CanvasAPI.update_lesson_grades` to do the user ID => canvas user ID look up if that's easier than doing it in the Rake task.

2020-08-27 21:17 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +          CanvasAPI.update_lesson_grades(canvas_course_id, canvas_assignment_id, grades_by_user_id)
it uses the canvas user id as the key here https://github.com/bebraven/platform/pull/334/files#diff-4f15adc169ba550856b204b4df59ca08R18

2020-08-27 21:19 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +          CanvasAPI.update_lesson_grades(canvas_course_id, canvas_assignment_id, grades_by_user_id)
This hash looks like 

```ruby
{
  canvas_course_id: {
    canvas_assignment_id: {
      canvas_user_id: grade,
    },
  },
}
```

2020-08-27 21:23 UTC, jessouyangbraven commented on lib/tasks/grade_lessons.rake
> +          CanvasAPI.update_lesson_grades(canvas_course_id, canvas_assignment_id, grades_by_user_id)
Ohhhhh. You have the user object. That makes sense!

2020-08-27 21:23 UTC, jessouyangbraven commented on lib/tasks/grade_lessons.rake
> +        grades[record.canvas_course_id][canvas_assignment_id][record.user.canvas_id] = LessonGradeCalculator.compute_grade(record.user, record.root_activity_id)
I think this has to be `record.user.id`.

2020-09-03 15:37 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +    Honeycomb.start_span(name: 'lesson_grade.compute_grades') do |span|
wasn't sure what to use for the span name, since I usually use Class.method and there are none here

2020-09-03 15:37 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +      .group(:user_id, :activity_id, :verb, :canvas_course_id, :canvas_assignment_id)
this query selects a bunch of things, but its the best I can do to limit the amount of records we're grabbing while still getting all the info we need to compute grades

2020-09-03 15:38 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +    }
here i filter down the query results to things that are unique by user id and root (without the quiz/question part) activity id

2020-09-03 15:42 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +          end
I'd like extra eyes here. this query seems to work, but I wasn't sure if I was selecting the right things to update.

2020-09-03 15:49 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +      .group(:user_id, :activity_id, :verb, :canvas_course_id, :canvas_assignment_id)
could also do this `group by` as a `distinct` instead, which would make the ruby cleaner, but `distinct` is usually waaaay slower.

2020-09-03 18:13 UTC, jessouyangbraven reviewed
The only thing to resolve how we're setting `new: false`. Everything else is non-blocking.

2020-09-03 18:13 UTC, jessouyangbraven commented on lib/tasks/grade_lessons.rake
> +          end
I might be missing something here, but don't we have all the `LessonInteractions` in `records` from line 6 to set `new: false` on? 

We do a bunch of filtering and manipulation on `records` to figure out the Canvas course/assignment/user IDs to use with `LessonGradeCalculator` and `CanvsAPI`, but aren't they in effect all the records we're doing the grade computations over?

2020-09-03 18:13 UTC, jessouyangbraven commented on lib/tasks/grade_lessons.rake
> +          end
This isn't something to address in this PR, but my mind went down the rabbit hole, so I'm going to record it here.

I don't think we can run multiple instances of this Rake task simultaneously. That's fine, but then I worry about atomicity violations even within a single run, since we're not using transactions anywhere and doing `LessonInteraction` `selects` multiple times throughout (here and `LessonGradeCalculator`). So it's possible we get `new` records between `LessonInteraction.where()`s. 

I think we're okay because we don't care about the `new` field when doing the actual grade computation. As long as we trigger computation at some point, we'll compute the right numerical value for the grade. 

The thing to go wrong here would be marking something as `new: false` before it was used to compute the grade and never triggering grade computation again because there are never any other `new` records that come in. 

All this to say, it's hard to reason about and I wouldn't want to be the one debugging why a bunch of students's grades are wrong some of the time.

2020-09-03 18:17 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +    Honeycomb.start_span(name: 'lesson_grade.compute_grades') do |span|
the parent of all of this is called `rake:grade:lessons`, so I could use e.g. `rake:grade:lessons:compute`? i'm not sure how span names are actually used outside the waterfall view, maybe that's good enough.

2020-09-03 18:29 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +          end
> all the LessonInteractions in records from line 6 to set new: false on?

Unfortunately, since we don't select `:id`, we can't use those `records` to reference the original rows in the table. They're essentially read-only and disconnected from the database as soon as we select them.

The risk of records being added in between when we select and grade, and us marking them as old without ever reading them, is an issue though. The only way I can think of to fix that is to stop using `group` and `uniq` to filter, and maintaining all the full records in memory until we've processed them, so we can mark the exact records we used as old. I'm worried that doesn't scale well. We could batch the select with `limit`, loop as many times as we need to until there are no longer new records, and do one `update_lesson_grades` per loop? More network requests, more SQL queries, but guaranteed correct results (still limited to 1 instance of the rake task at once). Is there a better way?

2020-09-03 18:34 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +      .group(:user_id, :activity_id, :verb, :canvas_course_id, :canvas_assignment_id)
I think the only worries are 1) the rake task lasts longer than a day and the heroku app restarts in the middle, and 2) we use up a bunch of cpu/memory on our heroku app and it autoscales and charges us more and/or makes the UI slower. Distinct scales poorly with large tables, even if you're only selecting a few records, to the point where I've seen `group by` take under a second while `distinct` takes minutes.

2020-09-03 18:55 UTC, jessouyangbraven commented on lib/tasks/grade_lessons.rake
> +      .group(:user_id, :activity_id, :verb, :canvas_course_id, :canvas_assignment_id)
Gotcha. Thanks!

2020-09-03 19:01 UTC, jessouyangbraven commented on lib/tasks/grade_lessons.rake
> +          end
I agree with the general approach you've outlined. And think we should guarantee correct results first and then work on improving any scaling issues. 

The only "better" way I can think of is multithreading the computation, since the grades are independent of each other. Going your approach of working out of local memory helps with this, since we won't have data races on the DB from the threads.

2020-09-03 19:26 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +          end
note to self: select max(id) before the first select, and use that to limit marking things in the second select

2020-09-04 17:12 UTC, sadleb requested changes

2020-09-04 17:12 UTC, sadleb commented on lib/tasks/grade_lessons.rake
> +        user = User.find(record.user_id)
If we add `user_canvas_id` to `LessonInteraction` we could avoid querying for the user when processing. Is that worth it? Are there other situations where we need the users's canvas_id when dealing with a `LessonInteraction`?

2020-09-04 17:12 UTC, sadleb commented on lib/tasks/grade_lessons.rake
> +    max_id = LessonInteraction.maximum(:id)
I would add a comment about the "why" behind this. Aka, interactions could come in while we're processing and we don't want to set them to processed after we've done the computation.

2020-09-04 17:12 UTC, sadleb commented on lib/tasks/grade_lessons.rake
> +              canvas_assignment_id).where('id <= ?', max_id).each do |record|
I don't think we care about the `updated_at` timestamp being reflected when setting `new: false` so I think we could just do `.where('id <= ?', max_id).update_all(new: false)` which would issue a single SQL statement and skip all the validations / callbacks.

2020-09-04 17:21 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +        user = User.find(record.user_id)
We need the user id too, I don't think adding a column to duplicate the canvas user ID in this table would be worth it. Selecting by id is an inexpensive query.

2020-09-04 17:27 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +    filtered_records = records.uniq {
Is `records = nil` enough to let the garbage collector run, if it needs to? I don't think it'd break anything.

2020-09-04 17:28 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +      .group(:user_id, :activity_id, :verb, :canvas_course_id, :canvas_assignment_id)
With our new max-id change, it's totally fault tolerant.

2020-09-04 17:29 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +    records = LessonInteraction
It's already in a span, but I can add `records.length` and `max_id` as a field.

2020-09-04 17:31 UTC, rshipp commented on app/models/lesson_interaction.rb
> +      activity_id.split('/')[0..-3].join('/')
I can, but the only part of the id that matters is the part in the comment there. `.split('/').[0..-3]` means "starting at the end, remove up to the second slash"

2020-09-04 18:14 UTC, rshipp commented on lib/tasks/grade_lessons.rake
> +    filtered_records = records.uniq {
Can't find a good answer to this. https://stackoverflow.com/questions/19523039/how-to-destroy-ruby-object 

I set it to nil but added a comment noting it's not guaranteed to do anything.

2020-09-04 18:39 UTC, sadleb commented on app/models/lesson_interaction.rb
> +      activity_id.split('/')[0..-3].join('/')
The comment is super helpful! I was trying to understand the `[0..-3]` and was completely confused.

2020-09-04 18:43 UTC, sadleb approved these changes
lgtm

2020-09-04 18:45 UTC, merged