Deprecate Registration Callback On User Model
bebraven/platform pull request #337
Opened 2020-09-01 22:07 UTC by skaex

2020-09-04 16:27 UTC, sadleb requested changes

2020-09-04 16:27 UTC, sadleb commented on app/services/account_creation.rb
> +    create_platform_user!
Ditto on `Honeycomb.start_span` comment above. Can we trace this and add the salesforce_id of the user we're creating as a field on the span?

2020-09-04 16:27 UTC, sadleb commented on app/views/admin/salesforce/init_sync_to_lms.html.erb
> +-->
I think we can delete this comment now. We have the rake task running. If we decide to integrate it with a button in Salesforce, let's just track that project in Asana.

2020-09-04 16:27 UTC, sadleb commented on app/views/devise/registrations/already_exists.html.erb
> +  <p>If believe you don't have an account, please <a href="mailto:support@bebraven.org">contact us here</a></p>
Did anyone provide this language? If not, my suggestion would be:

```
<h2>You've already signed up!</h1>
<div>
  <p>Please <a href="<%= new_session_path(resource_name) %>log-in here</a>.</p>
  <p>If believe you don't have an account, believe you don't have an account, please <a href="mailto:support@bebraven.org">contact us here</a></p>
```

Make sure I got the log-in link right. I didn't test the above.

2020-09-04 16:27 UTC, sadleb commented on lib/salesforce_api.rb
> +  @client = nil
Is this used?

2020-09-04 16:27 UTC, sadleb commented on spec/models/user_spec.rb
> +    xcontext "when salesforce_id is set" do
If theses are obsolete b/c account creation no longer happens when the user is created, delete these.

2020-09-04 16:27 UTC, sadleb commented on app/controllers/users/registrations_controller.rb
> +    end
Else log that it failed? What happens if the account fails to create?

2020-09-08 17:14 UTC, skaex commented on app/services/account_creation.rb
> +  def sf_client
I'll eventually move this to a mixin. That will also dry this up. This will happen in another PR.

2020-09-08 17:15 UTC, skaex commented on app/services/portal_account_enrollment.rb
> +    # Log warning for else case
I'll add the logger in another PR

2020-09-08 20:24 UTC, sadleb approved these changes
Generally looks good. This is too much to review too in depth, but assuming you've tested it sufficiently the code seems fine. Can you add information about how to test this to the PR description? If a future developer tracks changes back to this PR and doesn't have context about all the moving parts, it's nice to have an overview of the steps to take to execute and test the impacted features.

2020-09-08 21:08 UTC, merged