Add course resources, restructure courses
bebraven/platform pull request #341
Opened 2020-09-11 21:55 UTC by rshipp

2020-09-16 15:31 UTC, rshipp commented on app/models/base_course.rb
> +  def humanized_type
should this be here or in a helper?

2020-09-16 15:31 UTC, rshipp commented on app/models/course_membership.rb
> +  }, foreign_key: :base_course_id
what does this mean? and am I doing it right?

2020-09-16 15:32 UTC, rshipp commented on app/models/course_resource.rb
> +   "#{LtiLessonContentsProxy.proxy_url}#{LessonContentUtil.launch_path(course_resource_zipfile.key)}"
This is reusing lessoncontents stuff without renaming, should we rename it to be less specific now that we're using it in more places?

2020-09-16 15:34 UTC, rshipp commented on app/views/base_courses/_list.html.erb
> +              <%= link_to 'Edit', edit_polymorphic_path(base_course) %> |
polymorphic_path helpers resolve to the correct route for the object we pass in. in this case, /courses/1/edit or /course_templates/1/edit

2020-09-16 15:36 UTC, rshipp commented on app/views/base_courses/index.html.erb
> +<%= render 'list', base_courses: @base_courses.where(type: 'CourseTemplate') %>
I pulled the table out into a `_list` view to make it easier to change, and so we don't have two copies of it. I assume we'll heavily redesign this page at some point.

2020-09-16 15:36 UTC, rshipp commented on app/views/course_resources/show.html.erb
> +
not sure we still need this file

2020-09-16 15:37 UTC, rshipp commented on app/views/layouts/application.html.erb
> +    <%= content_for?(:headline_buttons) ? yield(:headline_buttons) : '' %>
we were using these `:headline` and `:headline_buttons` things all over, but never showed them anywhere, so I just threw them in here.

2020-09-16 15:39 UTC, rshipp commented on config/routes.rb
> +  resources :course_templates, controller: 'base_courses', type: 'CourseTemplate'
note you can technically visit `/courses` and `/course_templates` and go to the base_courses #index view. i didn't want to type out every possible view except index for the `only` param on these other two. :/

2020-09-16 15:42 UTC, rshipp commented on config/routes.rb
> +  get '/lti/course_resources', to: 'course_resources#lti_show'
i'm shoving LTI stuff in the course_resources controller again. :/

this one's different from lesson_contents and lti_assignment_selection in that course_resources has views that are available outside of the LTI flow. We should revisit renaming lesson_contents and/or lti_assignment_selection when we update the lesson/project/survey model stuff.

2020-09-16 15:44 UTC, rshipp commented on db/migrate/20200914175834_rename_program_refs_to_base_course.rb
> +    add_index :logistics, [:day_of_week, :time_of_day, :base_course_id], unique: true, name: :index_logistics_on_day_time_course
normally rails handles indexes for us, but since `base_course` is slightly more characters than `program`, the new index name was over the character limit. so I had to manually remove it and add it back with a shorter name.

2020-09-16 15:45 UTC, rshipp commented on lib/sync_to_lms.rb
> -      p = Program.new
note: I did not test sync_to_lms at all, I'm hoping our unit tests catch anything that would break here.

2020-09-16 15:46 UTC, rshipp commented on spec/factories/grade_category.rb
> +    association :base_course, factory: :course
evidently the `program` thing is shorthand for something like `association :program, factory: :program`, so I can't use `course` here because it needs to set `base_course_id`, not `course_id`.

2020-09-16 16:08 UTC, rshipp commented
Forgot to add CourseResource tests, working on that now...

2020-09-17 14:04 UTC, sadleb requested changes
To answer your Q in the PR about "does gradecategory/logistics/section" reference the right things? --> perhaps not in some spots, but I think we should fix that up when actually working on functionality that uses those instead of in this PR.

2020-09-17 14:04 UTC, sadleb commented on spec/factories/grade_category.rb
> +    association :base_course, factory: :course
Technically, I think this should use the `base_course` factory since a grade category applies to both course and course template. But I wouldn't go down that rabbit hole until we start working on something that actually uses grade category.

2020-09-17 15:37 UTC, rshipp commented on app/controllers/base_courses_controller.rb
> +  def set_type
I just copied from this https://youtu.be/2fH_V91b0H4?t=416 (which has some more context for why it's there), idk if it's a convention or just something they made up on the spot. I do think it's strange that it's not setting anything, but I'm not sure what else to call it. The params[:type] input is set in `config/routes.rb` where you pass in the `type` param as a string to the controller, so it's not really related to a class name.

2020-09-17 15:46 UTC, rshipp commented on app/controllers/course_resources_controller.rb
> +    if base_course&.course_resource
hm, I hadn't seen that. the only comparison i see is [this](https://rubyinrails.com/2017/11/17/safe-navigation-operator-ampersand-dot-in-ruby/#try-vs-safe-navigation). my initial reaction here is that it's more readable to use a core language feature than a Rails method.

2020-09-17 15:58 UTC, rshipp commented on app/models/user.rb
> +  def start_membership(base_course_id, role_id)
For things that expect specifically a `course`, I'd agree we should use `course` over `base_course`. But there's no such thing as a `course_id`, to me it seems more confusing to have `course_id` and `course_template_id`s than explicitly saying `base_course_id`. Maybe because I don't trust the Rails magic stuff and want a reminder of how this is reflected at the database level? In this specific case, if we renamed that variable, we'd have to pass in `base_course_id: course_id` to `create!`, which also seems confusing.

2020-09-17 16:00 UTC, rshipp commented on lib/sync_to_lms.rb
> +      p = BaseCourse.new
Yeah I assumed all the Salesforce stuff would stay - in our db diagram we had a `salesforce_program_id` which is totally separate from the now-removed `program_id`.

2020-09-17 16:02 UTC, rshipp commented on spec/factories/grade_category.rb
> +    association :base_course, factory: :course
We actually can't use the :base_course factory, since it would fail the `type` validation. That factory is only used in `models/base_course_spec.rb`, where it's called by `build`, not `create`, and so never uses the validations.

2020-09-17 16:04 UTC, rshipp commented on app/models/base_course.rb
> +  # from course
yeah, this was a "note to self" comment that i forgot to remove

2020-09-17 16:11 UTC, rshipp commented on app/models/base_course.rb
> +  belongs_to :course_resource, optional: true
I keep trying to understand what the difference is, but from what I can tell they aren't interchangeable? The way I understood it "the thing with the fkey reference gets a belongs_to", and in this case we have a course_resource_id in base_courses. (I've never seen a case where `belongs_to` actually makes sense as the name for this method, I wish it was called something else.)

2020-09-17 16:35 UTC, rshipp commented on spec/factories/grade_category.rb
> +    association :base_course, factory: :course
To put this another way bc I think this isn't very clear - factories are for making instances of objects, and `BaseCourse` should never have instances (it's basically an "abstract" class, if Ruby had those), so we must always choose a type if we want to test with an instance. If we need to test both, we should do both.

2020-09-18 15:05 UTC, sadleb commented on app/controllers/course_resources_controller.rb
> +    if base_course&.course_resource
word. i have yet to use `try` since that thread so I'm down for trying to stick with the ruby operator

2020-09-18 15:09 UTC, sadleb commented on app/controllers/base_courses_controller.rb
> +  def set_type
hmm, ok. maybe add a link to that video as a comment? i struggled to make heads from tails without having a deep understanding and experience with Single Table Inheritance and I'm sure future readers (including ourselves) will stumble on this again and be similarly confused.

2020-09-18 15:17 UTC, sadleb commented on app/models/base_course.rb
> +  belongs_to :course_resource, optional: true
Just went and re-read the stuff. This is the correct association. The name just throws me.

2020-09-18 15:18 UTC, sadleb commented on app/models/user.rb
> +  def start_membership(base_course_id, role_id)
Word. I'm down with sticking with `base_course_id` --> I'll just have to get used to having the keep the Rails magic stuff in mind instead of trying to make things as intuitive and specific as possible.

2020-09-18 15:26 UTC, sadleb approved these changes
Assuming the specs pass after that last commit, lgtm now.

2020-09-22 18:32 UTC, merged