Add Join User Creation
bebraven/platform pull request #344
Opened 2020-09-14 23:12 UTC by skaex

### Description
This adds the functionality that create a user on the join server. 

### Motivation and Context
There are still some features of the old join server that we need to get working e.g Braven Network.

https://app.asana.com/0/1172786304330247/1189555546176041
https://app.asana.com/0/1172786304330247/1189555546176042

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] I have added neccessary labels
- [x] My PR title follows the convention in the guide
- [x] I have assigned myself to the PR
- [x] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2020-09-15 17:38 UTC, sadleb requested changes

2020-09-15 17:38 UTC, sadleb commented on app/services/setup_portal_account.rb
> +    join_user = find_or_create_join_user!
Would it make more sense to have `UpdateJoinUsers` take a collection of users and then pass in the single user here and the collection from the maintenance task?

2020-09-15 18:13 UTC, sadleb commented on app/services/update_join_users.rb
> +    join_api_client.create_user(email: email, first_name: first_name,
If this fails will it be easy to troubleshoot and fix? E.g. if the Join server is in the middle of a restart?

2020-09-15 18:19 UTC, sadleb commented on app/services/setup_portal_account.rb
> +    join_user = find_or_create_join_user!
Also, for Highlander we won't want to create Join users. So if the ENV var isn't set we should skip the Join user creation logic both here and in the sync.

2020-09-16 17:10 UTC, skaex commented on app/services/update_join_users.rb
> +    join_api_client.create_user(email: email, first_name: first_name,
There's a rake that the will run periodically to cater for this edge case.

2020-09-17 12:29 UTC, sadleb requested changes

2020-09-17 12:29 UTC, sadleb commented on config/secrets.yml
> +  create_join_user_on_sign_up: <%= ENV.fetch('CREATE_JOIN_USER_ON_SIGN_UP') { true } %>
I don't think `CREATE_JOIN_USER_ON_SIGN_UP ` should be in the secrets file. We have other ENV vars that control behavior but aren't "secret" and the way we document their existence by adding them to `.env.example`. If you do that, then the code to check whether or not to run the "create on join" behavior can just check for `ENV["CREATE_JOIN_USER_ON_SIGN_UP"].present?` which I think it cleaner than looking for "true"

2020-09-17 12:29 UTC, sadleb commented on app/services/setup_portal_account.rb
> +    if Rails.application.secrets.create_join_user_on_sign_up.eql?(true)
This is where we can switch to `ENV["CREATE_JOIN_USER_ON_SIGN_UP"].present?` if we don't rely on `secrets`. You'd have to explicitly set this ENV var in your specs where you want to test this behavior.

2020-09-17 12:29 UTC, sadleb commented on spec/services/setup_portal_account_spec.rb
> +      described_class.new(salesforce_contact_id: nil).run
We don't have an explicitly stated "style-guide" for the use of `described_class` Other than `keypair_spec.rb` which is a copy/paste from another codebase, there is only one spot that uses it, so I think the existing style of our specs are more in line with using `SetupPortalAccount` vs `described_class`. 

I think if you want to introduce `described_class` as the new style we should do it in it's own PR where we go cut everything over to use it instead.

I personally think `described_class` is less readable than being explicit, but that's a discussion outside the scope of this PR.

2020-09-17 15:46 UTC, skaex commented on app/services/setup_portal_account.rb
> +      JoinAPI::JoinUser.new
It wouldn't make sense to return `nil` object because the caller is expecting a `JoinAPI::JoinUser.new` type object. We certainly can move the check upward to avoid it entirely.

2020-09-17 15:52 UTC, skaex commented on spec/services/setup_portal_account_spec.rb
> +      described_class.new(salesforce_contact_id: nil).run
It is better to use `described_class` in my opinion. For example, it becomes easier to refactor. However, I'll revert till we have a general consensus on this. PS: My linter will be screaming at me: https://rubocop.readthedocs.io/projects/rspec/en/read-the-docs/cops_rspec/#rspecdescribedclass

2020-09-17 17:58 UTC, sadleb approved these changes
I don't see a spec to test that if `CREATE_JOIN_USER_ON_SIGN_UP` isn't set, the `expect(join_api_client).not_to have_received(:create_user)` passes, but I assume you tested it out? If it's not too much trouble, I think you should add that spec. Either way, PR looks good enough to merge.

2020-09-17 18:16 UTC, merged