Security open redirect
bebraven/platform pull request #356
Opened 2020-09-29 16:40 UTC by rshipp

### Description

Task: https://app.asana.com/0/1174274412967132/1196136462683257/f

### Motivation and Context

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2020-09-29 16:42 UTC, rshipp commented on app/helpers/cas_helper.rb
> +  end
This logic seems overly complex, is there any way to simplify/railsify it?

2020-09-29 16:44 UTC, rshipp commented
not ready yet, whoops

2020-09-29 17:54 UTC, rshipp commented on app/helpers/cas_helper.rb
> +  ]
does this list look correct? is there anything else we want to add now? anything that redirects you to the platform login page must match against this list.

2020-09-29 18:56 UTC, jessouyangbraven commented on app/helpers/cas_helper.rb
> +  ]
I'm bad at regexes. Does this cover `staging` for booster and platform?

2020-09-29 18:58 UTC, jessouyangbraven commented
This looks reasonable to me. Going to let @sadleb review, though, because I don't feel solid on the CAS/security stuff.

2020-09-29 19:03 UTC, rshipp commented on app/helpers/cas_helper.rb
> +  ]
oh whoops. it does cover staging, but it also allows things like `evilbraven.org`... I'll have to tighten the regex

2020-09-29 19:14 UTC, rshipp commented on app/helpers/cas_helper.rb
> +  ]
ok I updated the regex and logic. I was also allowing `service=.evil.com`, which would have allowed redirects to e.g. `platform.bebraven.org.evil.com`.

2020-09-29 19:15 UTC, rshipp commented on app/helpers/cas_helper.rb
> +      return nil
new logic

2020-09-29 19:16 UTC, rshipp commented on app/helpers/cas_helper.rb
> +    /^(.+\.)?braven\.org$/,
tighter regex to allow `*.bebraven.org` or `bebraven.org` but not `evilbebraven.org`

2020-09-29 21:01 UTC, sadleb requested changes
I'm just unclear what happens if there is no `params['service']` or if that can happen.

2020-09-29 21:01 UTC, sadleb commented on app/helpers/cas_helper.rb
> +    parsed_service = Addressable::URI.parse(service)
Does this throw if `params['service']` is nil? Is that what we want?

2020-09-29 21:04 UTC, rshipp commented on app/controllers/cas_controller.rb
> +    safe_service_param = helpers.safe_service_url(params['service'])
the `if safe_service_param` below serves the same purpose.

2020-09-29 21:05 UTC, rshipp commented on app/helpers/cas_helper.rb
> +    parsed_service = Addressable::URI.parse(service)
nope
```
2.2.3 :041 > Addressable::URI.parse(nil)
 => nil
```
This is tested in the specs:
https://github.com/bebraven/platform/pull/356/files#diff-0b15deb88055ebbbc10eef66184751f4R40
If the param is nil, this function returns nil.

2020-09-29 21:11 UTC, rshipp commented
just found another issue. i thought only things starting with `.` were appended to the host, but that's not true, you can do it with anything. `service=test` redirects to `platform.bebraven.orgtest`. Rails' redirect_to is... really something.

2020-09-29 21:21 UTC, rshipp commented
OK fixed that too

2020-10-01 18:47 UTC, sadleb approved these changes
lgtm. Didn't realize the `Addressable::URI.parse(service)` behavior and didn't look closely enough at the specs to see the call with `nil` at the end.

2020-10-01 20:23 UTC, merged