First attempt at a working setup script
bebraven/platform pull request #360
Opened 2020-09-30 14:38 UTC by a-willis

A script that will build docker images, run db:create, and bring up the web server
This will be used by the development repository 

Test plan: run ./setup.sh. When done, visit platformweb:3020 in browser

2020-09-30 14:43 UTC, hcli-work requested changes

2020-09-30 14:43 UTC, hcli-work commented on setup.sh
> +docker-compose up platformweb
how does this even work? wouldn't it just hang here?

2020-09-30 14:43 UTC, hcli-work commented on setup.sh
> +docker-compose up platformweb
If this works and is really necessary, would you mind just putting in a small comment?

2020-09-30 14:45 UTC, a-willis commented on setup.sh
> +docker-compose up platformweb
The db:create command won't work without trying to run platformweb first. I'll add a comment to explain more

2020-09-30 14:50 UTC, hcli-work approved these changes
lgtm!

2020-09-30 14:52 UTC, merged

2020-10-08 15:21 UTC, sadleb commented on setup.sh
> +docker-compose run platformweb bundle exec rake db:create db:schema:load db:migrate db:seed
The steps in the README don't work? E.g. running
```
docker-compose up -d
docker-compose run platformweb bundle exec rake db:create db:schema:load db:migrate db:seed
```
And then restarting.