Using latest Heroku Platform DB snapshot
bebraven/platform pull request #392
Opened 2020-10-24 04:11 UTC by hcli-work

Added a script to download latest Heroku database snapshot from the braven-platform app.
Another script to restore from that snapshot and change all the passwords to our standard default one.

Test Plan: brought up all the repos and then attempted to login

2020-10-26 16:34 UTC, rshipp commented on docker-compose.yml
> +      - ./latest.dump:/latest.dump
did you mean to do this?

2020-10-26 16:36 UTC, rshipp commented on docker-compose.yml
> +      - ./latest.dump:/latest.dump
what will happen if the dump doesn't exist?

2020-10-26 16:39 UTC, rshipp commented
i'm not sure we want setup.sh to automatically pull a database snapshot. I worry that will make it too easy to e.g. accidentally publish modules to production. what's the usecase for this? note we try to keep db:seed / db:dummies such that you can run those and get reasonable test data in your local db.

2020-10-27 17:57 UTC, hcli-work commented on docker-compose.yml
> +      - ./latest.dump:/latest.dump
definitely not. thanks for the catch. I thought I was editing  a different file at the time. ugh.

2020-10-27 17:59 UTC, hcli-work commented on docker-compose.yml
> +      - ./latest.dump:/latest.dump
then it creates a latest.dump directory and things get really weird. it took me a while to figure out what was happening. this is the reason that in the download script there's a `rm -rf latest.dump*` before actually downloading.

2020-10-27 20:31 UTC, hcli-work commented
ready for re-review

2020-10-27 21:33 UTC, sadleb commented on docker-compose.yml
> +      - ./latest.dump:/latest.dump
I personally would put this under the `db` dir instead of at the root level, but it's not worth figuring out if it's a pain.

2020-10-27 21:33 UTC, sadleb commented on docker-compose/scripts/dblatest_restore.sh
> +ENCRYPTED_TEST_PASS='$2a$10$C2W0hszrbmpk8tkw0ViLFOXVFH1Sj6HAiMyGah6vdEoRUj7GK1KzO'
If we have a Booster and Highlander refresh option, this will need to be different.

2020-10-27 21:36 UTC, sadleb commented on docker-compose/scripts/dblatest_restore.sh
> +docker-compose exec platformdb pg_restore --verbose --clean --jobs 6 --no-acl --no-owner -U user -d platform_development /latest.dump
Most of us don't have 6 cores and even if we do we haven't allocated that many to the Docker environment. I think we should just use `2` jobs here (if any), otherwise, it's just going to lead to contention. For example: https://dba.stackexchange.com/questions/213734/why-might-a-parallel-pg-restore-command-take-hours-longer-to-complete-its-non-pa

2020-10-27 21:37 UTC, sadleb commented on setup.sh
>  docker-compose run platformweb bundle exec rake db:create db:schema:load db:migrate db:seed
Why do we need to run `db:schema:load db:migrate db:seed` if we're doing a restore from a snapshot?

2020-10-27 21:39 UTC, sadleb commented on setup.sh
> +./docker-compose/scripts/dblatest_restore.sh  # the first time has a couple of errors.
wut?!? This is just a `pg_restore` followed by a SQL command. What are the errors that you're seeing? I'm confused why running this again would fix anything...

2020-10-27 21:43 UTC, sadleb commented on setup.sh
> +./docker-compose/scripts/dblatest_download.sh
Seems like it's important where you run this script from. If you try and manually run it from the `./docker-compose/scripts` dir instead of as part of the `setup.sh` the dump will end up in the wrong dir.

Also, what's the ongoing development guidance (which we should also add to teh README). Do we just run `setup` once and then direction run `dbrefresh` occasionally when we want a fresh DB? Or is the plan to re-run setup each time you want a fresh DB?

2020-10-27 21:43 UTC, sadleb commented on setup.sh
>  #!/bin/zsh
Do we expect everyone to have `.zsh` or should we just use `sh`?

2020-10-27 21:45 UTC, sadleb commented on setup.sh
> +docker-compose down
What about `/etc/hosts` ? The original setup script run from the `development` repo sets this up and the dev env pretty much requires you do it and add `platformweb` (and other related apps that it needs to connect to locally if applicable, like join and canvas).

2020-10-28 00:40 UTC, hcli-work commented on .gitignore
> +*.dump
wow. didn't even know it would get built into the container image. that's frightening.

2020-10-28 00:40 UTC, hcli-work commented on docker-compose.yml
> +      - ./latest.dump:/latest.dump
oh whoops! this shouldn't even be here. I had originally thought about doing the pg_restore from the web container, but then figured why not do it from within the db container instead.

2020-10-28 00:40 UTC, hcli-work commented on docker-compose.yml
> +      POSTGRES_PASSWORD: password
when would someone change the database password?

the only dependency i'm aware of is that the password is stored both in the docker-compose.yml and also in .env.example. previously, the dependency would have existed between .env.example and .env.database.example. where else did I miss something?

2020-10-28 00:40 UTC, hcli-work commented on docker-compose/scripts/dblatest_restore.sh
> +docker-compose exec platformdb pg_restore --verbose --clean --jobs 6 --no-acl --no-owner -U user -d platform_development /latest.dump
that's fair. I'm going to try and see if I can dust off some shell scripting things and dynamically figure out the number of cores and then divide by two.

2020-10-28 00:40 UTC, hcli-work commented on docker-compose/scripts/dblatest_restore.sh
> +ENCRYPTED_TEST_PASS='$2a$10$C2W0hszrbmpk8tkw0ViLFOXVFH1Sj6HAiMyGah6vdEoRUj7GK1KzO'
why would this need to be different? won't the encrypted password still be stored in the same place on platform regardless of deployment?

i thought only the database snapshot download would be diffferent

2020-10-28 00:40 UTC, hcli-work commented on docker-compose/scripts/dblatest_download.sh
> +heroku pg:backups:download --app braven-platform
I think we'll need to add a parameter to the script so that it goes to appropriate heroku app to grab the download

2020-10-28 00:41 UTC, hcli-work commented on setup.sh
> +docker-compose down
/etc/hosts, AWS, Heroku, cloning repos is done from development scripts. that felt like the right place instead of here.

2020-10-28 00:43 UTC, hcli-work commented on setup.sh
>  #!/bin/zsh
I think using zsh is fine as that's the standard for Macs going forward (Lexi's laptop didn't have bash on it). I'm the only crazy one using Linux Mint. I installed zsh so that I could use this stuff.

2020-10-28 00:47 UTC, hcli-work commented on setup.sh
> +./docker-compose/scripts/dblatest_download.sh
good point. i hadn't considered being anywhere except in the root of the repo when running `setup.sh` Fix now or fix later?

in terms of guidance for dbrefresh, what's your take? my flow in the past has always been to grab a snapshot manually and then do the restores. that's only because it was occasionally useful for me to be able to pick a particular snapshot that I wanted to use so I'd download a couple and then restore from whichever one i wanted.

i renamed the old one because i didn't want to lose it in case I f'd this up.   :)

2020-10-28 09:23 UTC, sadleb commented on docker-compose.yml
> +      POSTGRES_PASSWORD: password
I don't see a reason to change it. I'm just going off the README. We should just remove the stuff in there about the DB password, hardcode it here and in `.env.example`, and remove `.env.database`

2020-10-28 09:25 UTC, sadleb commented on docker-compose/scripts/dblatest_restore.sh
> +ENCRYPTED_TEST_PASS='$2a$10$C2W0hszrbmpk8tkw0ViLFOXVFH1Sj6HAiMyGah6vdEoRUj7GK1KzO'
`SECRET_KEY_BASE` is different for each database which causes the same password to be hashed differently. It's in the same spot, but the value will be different.

2020-10-28 09:26 UTC, sadleb commented on setup.sh
>  #!/bin/zsh
I just installed `zsh` about a year ago and always used `bash` before. I think it's fine. If we ever hire a contractor or someone who refuses to use a Mac and does everything on Linux with some evangelical devotion to some other niche shell we'll let them fix all these up :)

2020-10-28 09:31 UTC, sadleb commented on setup.sh
> +./docker-compose/scripts/dblatest_download.sh
My take:

1. Account for where you run the script later. Not worth fixing now. It's fine to assume it's run from the root for now. 
2. I've pretty much never had an occasion to need a particular snapshot. Usually, if I'm doing a dbrefresh it's b/c I'm trying to troubleshoot some active production bug and just want my dev env to match prod or I fubar'd my local dev env so badly that I just need to start over. My vote is to keep the concept of a having a `dbrefresh` in each repo that lets you just blow away the database on demand and get it looking like prod without having to run the entire setup script. Setup feels like it should just be first time (and if you really want to nuke everything including your local git dirs and start completely from scratch)

2020-10-28 09:36 UTC, sadleb commented on docker-compose/scripts/dblatest_restore.sh
> +cpucores=`cat /proc/cpuinfo | grep "cpu cores" | uniq | awk -F'cpu cores\t:' '{print $2}'`
Getting fancy!

2020-10-28 15:57 UTC, rshipp commented on setup.sh
>  #!/bin/zsh
let's not write anything complex in zsh, but this seems fine. i don't know zsh at all, and it's not posix compliant by default.

2020-10-28 16:32 UTC, rshipp commented on docker-compose.yml
> +      - ./latest.dump:/latest.dump
I don't personally ever want a db dump. Will this still let me bring up the app without one?

2020-10-29 15:27 UTC, Rowantatai commented on docker-compose/scripts/dblatest_restore.sh
> +cpucores=`cat /proc/cpuinfo | grep "cpu cores" | uniq | awk -F'cpu cores\t:' '{print $2}'`
Unfortunately, this doesn't work on a mac.

2020-10-30 00:30 UTC, hcli-work commented on docker-compose.yml
> +      - ./latest.dump:/latest.dump
it will. you just would have to bring things up manually yourself. what's the concern about not wanting a db dump?

2020-10-30 00:30 UTC, hcli-work commented on docker-compose.yml
> +      POSTGRES_PASSWORD: password
will do

2020-10-30 00:30 UTC, hcli-work commented on docker-compose/scripts/dblatest_restore.sh
> +ENCRYPTED_TEST_PASS='$2a$10$C2W0hszrbmpk8tkw0ViLFOXVFH1Sj6HAiMyGah6vdEoRUj7GK1KzO'
oh boy. okay. let me get this working for Accelerator/BravenX first.

2020-10-30 00:30 UTC, hcli-work commented on setup.sh
> +./docker-compose/scripts/dblatest_download.sh
so maybe change dbrefresh to essentially just run the latest download and then run restore?

2020-10-30 00:44 UTC, hcli-work commented
alright. I have rebased and brought back the dbrefresh.sh script which just invokes the download and restore scripts

2020-11-03 15:49 UTC, rshipp commented on docker-compose.yml
> +      - ./latest.dump:/latest.dump
the data in production is not useful for local dev, and if I load the production db i'd have to set up my local db all over again.

2020-11-11 03:36 UTC, sadleb commented on setup.sh
>  docker-compose run platformweb bundle exec rake db:create db:schema:load db:migrate db:seed
I think we can remove. Those are for setting up a database using rails stuff. For restoring from a dump, you just need to have the database and be able to connect to it but the restore should add the tables and data.

2020-11-11 03:42 UTC, sadleb commented on setup.sh
> +./docker-compose/scripts/dblatest_restore.sh  # the first time has a couple of errors.
My hunch is that the default heroku dump wasn’t done using the “clean” flag meaning that there are no “drop table” commands in there. I’m not sure what a pg_restore clean does without the dump itself being done with that flag, but maybe it just truncates instead of dropping tables? What we really want is a completely fresh db to restore into so rather than running it twice I feel like we should just drop the database and recreate it before restoring into the fresh db. I feel like that’s the approach I’ve taken in the past when I’m really trying to blow a db away and restore a freshy

2020-11-11 03:45 UTC, sadleb commented on setup.sh
> +./docker-compose/scripts/dblatest_download.sh
Yup

2020-11-25 16:45 UTC, hcli-work reviewed
realized i never submitted my comment

2020-12-01 16:53 UTC, sadleb requested changes
Main change i'm unclear about is the encrypted password part.

2020-12-01 16:53 UTC, sadleb commented on docker-compose/scripts/dblatest_download.sh
> +heroku pg:backups:download --app $app
Does this default to storing it in the `latest.dump` file?

2020-12-01 16:53 UTC, sadleb commented on docker-compose/scripts/dblatest_restore.sh
> +docker-compose exec platformdb pg_restore --verbose --clean --jobs 2 --no-acl --no-owner -U user -d platform_development /latest.dump
Is the `/latest.dump` b/c it reads from the file inside the container? Should it be `./latest.dump` or is it really at the root of the filesystem in there? Would it be better to just pipe it from outside the container using `cat latest.dump | docker-compose exec -T platformdb pg_restore --verbose --clean --jobs 2 --no-acl --no-owner -U user -d platform_development`

2020-12-01 16:53 UTC, sadleb commented on docker-compose/scripts/dblatest_restore.sh
> +ENCRYPTED_TEST_PASS='$2a$10$C2W0hszrbmpk8tkw0ViLFOXVFH1Sj6HAiMyGah6vdEoRUj7GK1KzO'
Did this actually work for Accel/BravenX? Seems like you added other stuff to switch apps but didn't update this?

2020-12-03 21:39 UTC, hcli-work commented on docker-compose/scripts/dblatest_download.sh
> +heroku pg:backups:download --app $app
it does

2020-12-03 21:42 UTC, hcli-work commented on docker-compose/scripts/dblatest_restore.sh
> +docker-compose exec platformdb pg_restore --verbose --clean --jobs 2 --no-acl --no-owner -U user -d platform_development /latest.dump
yes. it's at the filesystem root via a volume mounted in the docker-compose.yml
i can try piping it in. i'm not sure if it'll work though since these are binary dumps

2020-12-03 21:55 UTC, hcli-work commented on docker-compose/scripts/dblatest_restore.sh
> +ENCRYPTED_TEST_PASS='$2a$10$C2W0hszrbmpk8tkw0ViLFOXVFH1Sj6HAiMyGah6vdEoRUj7GK1KzO'
It did! I was kinda surprised, too, but was able to login as booster.admin@bebraven.org after refreshing from the  snapshots for braven-booster and braven-platform-booster.

2020-12-03 21:59 UTC, hcli-work commented on docker-compose/scripts/dblatest_restore.sh
> +docker-compose exec platformdb pg_restore --verbose --clean --jobs 2 --no-acl --no-owner -U user -d platform_development /latest.dump
confirmed it doesn't work from stdin unfortunately when there is parallelism set

2020-12-03 22:08 UTC, hcli-work reviewed
Determined that piping a dump file is not compatible with parallelism while restoring.
Re-confirmed that grabbing snapshots from both Accel and Booster work.

2020-12-07 14:45 UTC, sadleb approved these changes
lgtm

2020-12-07 16:54 UTC, rshipp commented on docker-compose.yml
> +      - ./latest.dump:/latest.dump
yes, there's nothing in the production dbs except whatever projects Helen's working on at the time. local dev dbs have users in sections in courses, with projects and modules, everything we use to develop with.

2020-12-08 01:48 UTC, merged