DRAFT. Proof-of-concept for SurveySubmissions
bebraven/platform pull request #403
Opened 2020-10-28 03:43 UTC by jessouyangbraven

Hax. You can then do https://platformweb/base_course_custom_content_versions/{id}/survey_submissions/new and see a SurveySubmission form.

### Description

### Motivation and Context

### Screenshots (if appropriate):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2020-10-28 03:54 UTC, jessouyangbraven reviewed
Notes to self so I don't forget.

2020-10-28 03:54 UTC, jessouyangbraven commented on app/controllers/custom_contents_controller.rb
> +  before_action :set_course_templates, only: [:new, :edit]
Shows list of `CourseTemplate`s that you can Publish to from Content Editor.

2020-10-28 03:54 UTC, jessouyangbraven commented on app/controllers/custom_contents_controller.rb
> +  before_action :set_course_template, only: [:publish]
Set the `CourseTemplate` you're going to save a new version to when you Publish from the Content Editor.

2020-10-28 03:54 UTC, jessouyangbraven commented on app/controllers/custom_contents_controller.rb
> +    # TODO: CanvasAPI assignment create on template
This could/should? also move to the Course Management page. I did this so I could quickly do this without the console.

2020-10-28 03:54 UTC, jessouyangbraven commented on app/controllers/survey_submissions_controller.rb
> +class SurveySubmissionsController < ApplicationController
Maybe we use regular polymorphism here and have a `SubmissionsController` because a lot of this logic is similar to `ProjectSubmissionsController`, despite `SurveySubmission` and `ProjectSubmission` having different data/tables (for now).

2020-10-28 03:54 UTC, jessouyangbraven commented on app/controllers/survey_submissions_controller.rb
> +    # TODO: Save the actual answers
Here's the diagram with `survey_submissions` added to it: https://dbdiagram.io/d/5f98e3c03a78976d7b797320

It's worth discussing how we want to store the survey responses.

2020-10-28 03:54 UTC, jessouyangbraven commented on app/controllers/survey_submissions_controller.rb
> +    # or Canvas Submissions API
Also worth investigating/discussing whether we want to use the Canvas Submission API or LTIAdvantage API here.

2020-10-28 03:54 UTC, jessouyangbraven commented on app/javascript/components/ContentEditor.js
> +    }
"Publish" behavior is different: we only allow it on content that's been saved already. And we have a drop-down of course templates that you can publish to.

This is really for me at the moment, so it can move to course management, whenever we decide how we create and add content to templates.

2020-10-28 03:54 UTC, jessouyangbraven commented on app/models/custom_content.rb
> +    new_version
Minor API change because I was sick of having to do `save_version!` and immediately after call `last_version`.

2020-10-28 03:54 UTC, jessouyangbraven commented on app/policies/survey_submission_policy.rb
> +class SurveySubmissionPolicy < ApplicationPolicy
This is just like `ProjectSubmissionPolicy` with `Project` => `Survey`. It might be worth figuring out how to do:

  `class SurveySubmissionPolicy < SubmissionPolicy`
  `class ProjectSubmissionPolicy < SubmissionPolicy`

if we think these submission types are going to stay the same.

2020-10-28 03:54 UTC, jessouyangbraven commented on app/views/custom_contents/_custom_content.json.jbuilder
> +json.extract!(
This is an actual syntax error I introduced and never hit the code, so I could go fix this in an existing PR somewhere.

2020-10-28 03:54 UTC, jessouyangbraven commented on app/views/survey_submissions/index.html.erb
> +<h1>Project Submissions</h1>
Can we share views between project/survey submissions? I copy-pasted a lot to just get this running.

2020-10-28 03:55 UTC, jessouyangbraven commented on app/javascript/components/ContentEditor.js
> -                              />
I think this means I can do a migration to get rid of `course_id`, `secondary_id`, and `course_name` now that we're on the highlander branch.

2020-10-28 19:32 UTC, jessouyangbraven commented on app/controllers/survey_submissions_controller.rb
> +    # or Canvas Submissions API
Don't need grades, just need some indication to the fellow that it's been done. Don't need a way to view actual submission contents.

2020-10-28 19:33 UTC, jessouyangbraven commented on app/javascript/components/ContentEditor.js
> +    }
Remove Publish button Content Editor UI. Leave #publish button, add Asana task.

2020-10-28 22:30 UTC, jessouyangbraven commented on app/controllers/survey_submissions_controller.rb
> +    # TODO: Save the actual answers
`survey_submission_key_values` table added to diagram above.

2020-10-29 15:52 UTC, sadleb requested changes

2020-10-29 15:52 UTC, sadleb commented on app/models/survey_submission.rb
> +  scope :for_custom_content_version_and_user, ->(c, u) { where(base_course_custom_content_version: c, user: u) }
Should this be `for_base_course_custom_content_version_and_user` ? I know it's long, but it's for a join model and not for the underlying content version.

2020-10-29 16:16 UTC, sadleb commented
I think we should get in the habit of both linking to the dbdiagram and dropping a screenshot in here. I'm imaging years from now when the account is deleted or dbdiagram shuts down, it would still be nice to have the screenshot to make things more concrete even if the link breaks.

2020-10-29 17:25 UTC, rshipp commented on app/models/survey_submission.rb
> +  scope :for_custom_content_version_and_user, ->(c, u) { where(base_course_custom_content_version: c, user: u) }
I'd suggest deleting this scope instead. we only use it once.

2020-10-29 21:31 UTC, sadleb approved these changes
lgtm

2020-10-30 01:54 UTC, merged