DRAFT. Proof-of-concept: save, render responses for impact survey submission
bebraven/platform pull request #409
Opened 2020-10-29 02:51 UTC by jessouyangbraven

### Description

### Motivation and Context

### Screenshots (if appropriate):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2020-10-29 03:14 UTC, jessouyangbraven commented on app/controllers/survey_submissions_controller.rb
> +      if params[input_name]
This relies on how `<form>` submissions automatically behave, which is why I'm using the `name` attribute and not the `id`.

In theory we could use retained data here, since it's unique, and already on the `id`, so we could get it just by copying it over to `name.

But retained data has always been weird, so maybe there's another way to do this?

I guess the question is whether these have to be globally unique, or just unique to the each project/survey version.

2020-10-29 03:14 UTC, jessouyangbraven commented on app/controllers/survey_submissions_controller.rb
> +          input_value: params[input_name],
We need to sanitize this. Does Rails have a utility function I can call?

2020-10-29 03:14 UTC, jessouyangbraven commented on app/models/survey_version.rb
> +  end
This is so gross. Ryan wrote `xapi_assignment.js` so we wouldn't have to use `nokogiri` for `ProjectSubmission`. Should I do something similar? We'll probably need it again when we store the project submission responses in platformdb?

2020-10-29 03:14 UTC, jessouyangbraven commented on config/routes.rb
>      resources :project_submissions, :path => 'submissions', only: [:show, :new, :create]
I was going to get rid of the aliased path, but then I realized it'd probably break what Brian's working on. Should we get rid of this in the future so it's not ambiguous which submission?

2020-10-29 20:35 UTC, jessouyangbraven reviewed
Updated based on our discussion during stand-up. The task for updating Canvas is here: https://app.asana.com/0/1174274412967132/1198971448730205

2020-10-29 20:35 UTC, jessouyangbraven commented on app/controllers/survey_submissions_controller.rb
> +  end
@rshipp, I know we decided against Nokogiri parsing during the stand up, but there's a lot of stuff in the `params` when you submit a form and I get more weirded out about saving that to the DB than parsing input names out here. 

Feel free to push back if you feel strongly or have a better way of sanitizing form inputs.

2020-10-29 21:39 UTC, sadleb commented on app/controllers/survey_submissions_controller.rb
> +        SurveySubmissionResponse.create!(
`SurveySubmissionAnswer` ?

2020-10-29 22:08 UTC, sadleb requested changes
Main change blocking merge is the re-naming of SurveySubmissionResponse. The rest of the feedback is not merge blocking.

2020-10-29 22:08 UTC, sadleb commented on app/controllers/survey_submissions_controller.rb
> +  end
I'm fine with this but curious if Ryan wants to push harder to not do this. Basically, no real strong opinion either way here.

2020-10-29 22:08 UTC, sadleb commented on app/models/survey_submission.rb
> +  has_many :survey_submission_responses
think this needs to be rebased off the other branch where you changed response to answer.

2020-10-29 22:08 UTC, sadleb commented on app/policies/survey_submission_policy.rb
> +    SurveyVersionPolicy.new(user, record.survey_version).show?
Are these all meant to be `show`? Makes sense to me that if you can see it you can work on it and submit it, but just making sure. I could see a different policy in the future if we ever show the actual responses to TAs where they should only be able to see and not answer or submit.

2020-10-29 22:08 UTC, sadleb commented on app/views/survey_submissions/new.html.erb
> +  <div class="bz-assignment">
When we get to the future PR to actually build the UI, we should consider whether refactoring the old `bz-assignment` CSS makes sense now or later. I sort of lean towards making this `braven-survey` or something just so that when we start on the UI we'll immediately notice that the project styling isn't applying and be forced to make a decision.

2020-10-29 22:08 UTC, sadleb commented on app/views/survey_submissions/show.html.erb
> +<div class="bz-assignment">
Ditto on the `bz-assignment` feedback.

2020-10-30 01:43 UTC, jessouyangbraven commented on app/controllers/survey_submissions_controller.rb
> +    params.require([:base_course_custom_content_version_id])
Oops. `[]` is vestigial. I was doing something where I was trying to require multiple parameters, which I turned out to not need. I can get rid of this!

2020-10-30 01:46 UTC, jessouyangbraven commented on app/policies/survey_submission_policy.rb
> +    SurveyVersionPolicy.new(user, record.survey_version).show?
Yup, this was intentional. It's worth noting a caveat with the controller's `#create` action. The pundit `create?` will pass, but when we eventually update Canvas, the Canvas API will error out if you try to create a line item/submission for an assignment if you're not a student enrolled in the course. When we get to the Canvas part of survey submissions, it'll be worth thinking about if `create?` should have its own logic so we fail in our controller rather than waiting until we get to Canvas.

2020-10-30 01:47 UTC, jessouyangbraven commented on app/views/survey_submissions/new.html.erb
> +  <div class="bz-assignment">
I agree with having our own CSS and not using any of the `bz-*` stuff anymore. The `bz-assignment` was just to get it look presentable quickly in the initial UI.

2020-10-30 10:30 UTC, sadleb approved these changes

2020-10-30 10:30 UTC, merged