Stop nesting base_course_custom_content_versions under base_courses
bebraven/platform pull request #427
Opened 2020-11-04 00:10 UTC by jessouyangbraven

### Description

### Motivation and Context

### Screenshots (if appropriate):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2020-11-04 00:24 UTC, jessouyangbraven commented on app/views/base_courses/_form.html.erb
> +<%= link_to 'Add Project', new_base_course_custom_content_version_path(base_course_id: base_course.id, type: 'Project'), class: 'btn btn-sm btn-outline-secondary' %>
In un-nested version of `new...path()`, we explicitly pass `base_course_id` as a query parameter now instead of having  `new_base_course_base_course_custom_content_version_path(base_course,...` do it automatically.

2020-11-04 00:24 UTC, jessouyangbraven commented on app/views/base_course_custom_content_versions/new.html.erb
> +      <%= form_with url: base_course_custom_content_versions_path do |form| %>
We didn't need the nested path to the `#create` method even before this PR, since we're passing the `base_course_id` and `custom_content_id` are inputs that get submitted with the form.

2020-11-04 00:24 UTC, jessouyangbraven commented on app/views/base_course_custom_content_versions/_list.html.erb
> +                <%= link_to 'Delete', base_course_custom_content_version_path(bcccv.id), method: :delete,
We didn't need the nested paths to `#update` and `#delete` because we need a pre-existing `bcccv` object to do those actions, so passing its ID suffices.

2020-11-04 00:24 UTC, jessouyangbraven commented on app/controllers/base_course_custom_content_versions_controller.rb
> +  before_action :set_model_instances, except: [:new]
This is necessary because I removed the `Nestable` `nested_resource_of` that automatically set `@base_course` for us.

2020-11-04 00:24 UTC, jessouyangbraven commented on app/controllers/base_course_custom_content_versions_controller.rb
> +    )
These are `before_action`s specifically for `#new`. 

Currently, we always create a BCCCV in the context of a `CourseTemplate` and this controller relies pretty heavily on that assumption for the `#new` action.  So we can currently expect that `params[:base_course_id]` is going to be set. I could add a `params.require()` so it fails more obviously, but it'll fails on `.find(nil)` too, so I wasn't sure which is preferable. 

I don't know how much flexibility we should support on the `#new` action in general for this controller.
- :base_course_id - currently supported, I'm going to add a new 
- :custom_content_id - not supported, the custom content would be fixed, you get to select the course template from a drop down (if we ever wanted to support Publish from the content editor for example)
-  neither - also not supported, we would show two drop downs and you get to decide which template and which content (it'd be hard to filter the drop-downs dynamically, so we'd have to make sure that #create or the model checks that we don't add a customcontent to a template twice)

2020-11-04 18:51 UTC, rshipp approved these changes
tentatively approving because I don't see anything that stands out as bad but i don't understand all of

2020-11-04 19:46 UTC, jessouyangbraven commented
> tentatively approving because I don't see anything that stands out as bad but i don't understand all of

Let's talk about it in the standup. This PR only makes sense in the context of making things more intuitive to developers, so I'd like to get feedback on what's confusing here!

2020-11-04 20:15 UTC, jessouyangbraven commented on config/routes.rb
> -  resources :base_course_custom_content_versions, only: [] do
Put back `:new` under `:base_courses`. Add comment on why this is nested.

2020-11-04 20:32 UTC, sadleb requested changes
I'm thinking it's cleaner to split out the logic into separate before actions. Thoughts?

2020-11-04 20:32 UTC, sadleb commented on app/controllers/base_course_custom_content_versions_controller.rb
> -  before_action :verify_can_edit!
I personally like this as a separate `before_action` but I'm fine either way.

2020-11-04 20:32 UTC, sadleb commented on app/controllers/base_course_custom_content_versions_controller.rb
> +    @base_course_custom_content_version.update!(
Nice, this is cleaner. Generally, ruby encourages lots of small methods and stringing them together to make things readable.

2020-11-04 20:32 UTC, sadleb commented on app/controllers/base_course_custom_content_versions_controller.rb
> +  private
I feel like we're wrestling with moving the indentation and line break of the `private` between these two options. Do you think it's more readable this way?

2020-11-04 20:32 UTC, sadleb commented on app/controllers/base_course_custom_content_versions_controller.rb
> +  def set_model_instances
The other option would be to have `set_base_course` and `set_custom_content` with each being responsible for something like
```
def set_base_course
  @base_course = @base_course_custom_content_version&.base_course
  @base_course = BaseCourse.find(params[:base_course_id]) if params[:base_course_id]
end
```
so that the controller would have
```
before_action :set_base_course
before_action :set_custom_content
before_action :verify_can_edit!
```
Which is more readable / maintainable? Separate or a big `set_model_instances` that does all the logic?

2020-11-04 20:32 UTC, sadleb commented on app/controllers/base_course_custom_content_versions_controller.rb
> +    @base_course = BaseCourse.find(params[:base_course_id])
If we separate out the `set_model_instances` you wouldn't have to call this here.

2020-11-04 20:33 UTC, sadleb commented on app/controllers/base_course_custom_content_versions_controller.rb
> +    @base_course = BaseCourse.find(params[:base_course_id])
Ditto on the above about splitting up `set_model_instances`

2020-11-04 22:38 UTC, jessouyangbraven commented on app/controllers/base_course_custom_content_versions_controller.rb
> +  private
I generally find the `private` rules in Ruby confusing and haven't found any style convention that makes it clear what's going on.

I was under the impression that everything after `private` was made private. So the line break makes sense to me, because it doesn't just apply to the one `def`. We could indent everything under the private over one, but that might be overkill? 

I'm agnostic; I'm happy to do whatever so long as we're consistent.

2020-11-04 22:38 UTC, jessouyangbraven commented on app/controllers/base_course_custom_content_versions_controller.rb
> +    @base_course = BaseCourse.find(params[:base_course_id])
Good call on splitting up `set_model_instances`.

2020-11-04 22:38 UTC, jessouyangbraven commented on app/controllers/base_course_custom_content_versions_controller.rb
> -  before_action :verify_can_edit!
Sorry! Missed this one because I was scanning the right-hand column. I'm okay either way. I'll either put it back in `verify_can_edit!` on its own or change the other action to `:set_base_course!` since it can throw now. Will update PR after I get through some assignment submissions stuff.

2020-11-04 23:25 UTC, sadleb commented on app/controllers/base_course_custom_content_versions_controller.rb
> +  private
My vote is for sticking with no indentation, aka it applies to the whole class, and leaving a line break. So what it was before this diff. We should prob add or edit the codacy linter rules but I’m not inclined to take that on at the moment and have admittedly been very lax about checking codacy results over this past month or two.

2020-11-04 23:38 UTC, sadleb approved these changes
Lgtm!

2020-11-05 00:24 UTC, jessouyangbraven commented on app/controllers/base_course_custom_content_versions_controller.rb
> +  private
Re: Codacy, @rshipp mentioned it's been down for a while. Which explains why I haven't gotten those emails in a while.

2020-11-05 19:40 UTC, merged