Update sync for nlu
bebraven/platform pull request #476
Opened 2020-11-24 18:38 UTC by skaex

### Description
This updates the way sync to lms works for NLU program.

### Motivation and Context
NLU has a slightly different requirement for how fellows join our system. The fellow need to have their accounts created when running a sync to lms.

https://app.asana.com/0/1185361437008970/1199201476879535

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] I have added neccessary labels
- [x] My PR title follows the convention in the guide
- [x] I have assigned myself to the PR
- [x] I have requested reviews from team members
- [x] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2020-12-01 18:47 UTC, sadleb requested changes
I think this stuff is confusing enough without the full higher level context that some clarifying comments are needed. I also think we need to write a `spec` or two for this to make it clear that the intended behavior is b/c this seems like a really likely place that some future developer will want to refactor and cleanup with confidence that they aren't breaking the expected logic.

2020-12-01 18:47 UTC, sadleb commented on app/services/account_creator.rb
> +    @for_nlu = for_nlu
I think it would be cleaner if you stored the `sign_up_params` in an instance variable. Then in `password_params` do all the logic to convert `sign_up_params` to `password_params`.

2020-12-01 18:47 UTC, sadleb commented on app/services/account_creator.rb
> +      { password: password, password_confirmation: password }
Can you add a comment about why this is? E.g. we don't actually use the password for NLU, they go through their own SSO server but we need some password to be there for Devise. Or is that not what this is doing?

2020-12-01 18:47 UTC, sadleb commented on app/services/setup_portal_account.rb
> +      user.skip_confirmation!
If someone just stumbled across this code for the first time they would have no clue why we skip it. Can you add a comment about why?

2020-12-01 18:47 UTC, sadleb commented on app/services/setup_portal_account.rb
> +      "#{sf_participant.student_id}@nlu.edu"
Ditto on comments. If we can't more cleanly split the NLU specific logic out from the normal logic with a big comment about how NLU is different and what the implications are, then I think you need to add comments inline where you do the special logic to help folks understand why this code is here. Aka: this is the email format that the NLU SSO server sends sends in the authentication exchange and needs to match with the email Canvas has. Actually, is that the case? Did you test this? I have a vague recollection that we had to do something special somewhere to make sure the NLU SSO server actually could successfully authenticate with Canvas and match up the user.

2020-12-01 18:47 UTC, sadleb commented on lib/salesforce_api.rb
> +      "SELECT Id, Name, Target_Course_ID_in_LMS__c, LMS_Coach_Course_Id__c, School__c, Program_Shortname__c, " \
Why use shortname instead of school? Is school just a Salesforce ID? Seems more brittle to rely on the shortname vs the actual school name.

2020-12-01 20:01 UTC, skaex commented on lib/salesforce_api.rb
> +      "SELECT Id, Name, Target_Course_ID_in_LMS__c, LMS_Coach_Course_Id__c, School__c, Program_Shortname__c, " \
I'll change this. However, IMO the shortname is used internally and we have more control about how it'll change. Even on SF, it looks easier to update the school name than the shortname.

2020-12-02 18:27 UTC, sadleb commented on lib/salesforce_api.rb
> +      "SELECT Id, Name, Target_Course_ID_in_LMS__c, LMS_Coach_Course_Id__c, School__c, Program_Shortname__c, " \
Go with whichever is less brittle. If you think that's shortcode, works for me.

2020-12-03 21:03 UTC, sadleb approved these changes
If this were for the Highlander codebase I’d want to spend a little more on the specs, but I think this is good enough to merge for the Portal code. Thanks for taking action on all the feedback!

2020-12-03 21:05 UTC, merged