Fix Course routes.
bebraven/platform pull request #487
Opened 2020-12-02 22:21 UTC by sadleb

### Description
After getting rid of the course_management paths, it exposed an issue
where `/courses/launch` was being interpreted as trying to `show` the course
with `id=launch`. The duplicate `resources :courses` routes seemed to cause
the confusion. Consolidating it makes it all work again.

Note: we still need to revisit whether all these routes should be defined
and/or what authorization we should put in place for them to avoid mistakes
against real, launched courses or real fully populated course templates. Task
for that: https://app.asana.com/0/1174274412967132/1199503585782989

### Test Plan:
Make sure you can go to https://platformweb/courses and use the Launch New Program button as well as edit/delete/add a course template

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2020-12-02 22:36 UTC, rshipp requested changes

2020-12-02 22:36 UTC, rshipp commented on config/routes.rb
> +
this would break peer review submissions, since it relies on the parent course being set

2020-12-02 22:43 UTC, sadleb commented on config/routes.rb
> +
It's nested under courses. The diff is hard to see. It's
```
resources :courses do
  ...
  resources :peer_review_submissions, only: [:new, :create]
  ...
end
```

2020-12-03 01:03 UTC, jessouyangbraven approved these changes

2020-12-03 16:26 UTC, merged

2020-12-03 16:49 UTC, rshipp commented on config/routes.rb
> +
ohh I see, whoops