Add some CSS styling for Peer Reviews.
bebraven/platform pull request #489
Opened 2020-12-03 13:18 UTC by sadleb

### Description
This is just a first pass, but I'm pretty happy with it. We used the
pinned screenshot in this task: https://app.asana.com/0/1174274412967132/1193980665758237
as inspiration. This was from a prototype we did in FormAssembly.

One thing to note is that this CSS is very specific to this form.
It was a challenge to get the radio list with 5 options and inline
text to lay out nice horizontally and switch to vertical at the
right media breakpoints. See the big comment in
`peer_review_submissions.scss` for why we have a weird hard-coded
non-standard media breakpoint in there. I did pretty extensively check
how the form looked at different screen sizes when shown inside Canvas.

### Screenshots (if appropriate):
<details><summary>Before</summary><img width="800" src="https://user-images.githubusercontent.com/5596986/101022766-d5233c00-353f-11eb-8a28-a4a669dff576.png">
</details>

### After (laptop)
<img width="800" src="https://user-images.githubusercontent.com/5596986/101022881-fa17af00-353f-11eb-9081-acfd8756f085.png">

### After (mobile)
<img width="400" src="https://user-images.githubusercontent.com/5596986/101022971-1b789b00-3540-11eb-8ceb-7d2d22e5815e.png">

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2020-12-03 13:21 UTC, sadleb commented on app/assets/stylesheets/layouts/lti_canvas.scss
> +  padding: 0;
We already show everything with left and right margins. This allows a Bootstrap container inside to be able to take advantage of the full width of the iframe when arranging content in a grid.

2020-12-03 13:24 UTC, sadleb commented on app/views/peer_review_submissions/new.html.erb
> -<div class="peer-review">
Moved this wrapper up to the parent `bv-lti-container` so that we could set the media breakpoints relative to the full iframe space we have.

2020-12-03 13:28 UTC, sadleb commented on app/views/peer_review_submissions/new.html.erb
> +          <div class="container-fluid p-0">
Full width, no-gutter, container to handle laying out the radiolist horizontally vs vertically. Note that I tried using Boostrap's `form-check` and `form-check-inline` stuff but it was just making it worse and giving me a headache. We really just need 5 columns that have nice margins/padding that switch to vertical at the point where they can no longer fit.

2020-12-03 16:55 UTC, rshipp commented on app/assets/stylesheets/peer_review_submissions.scss
> +    text-transform: capitalize;
let's remove this, we don't want to mess up capitalization in peoples names. i'd rather show a lower-case name for someone who entered it that way than broken capitalization for someone who entered their name correctly.

2020-12-03 16:56 UTC, rshipp commented on app/assets/stylesheets/peer_review_submissions.scss
> +    text-transform: capitalize;
This Makes The Questions Read Very Stilted To Me, can we get rid of it? these are legends, not headings, so there's no consistency issue here.

2020-12-03 16:58 UTC, rshipp commented on app/views/peer_review_submissions/new.html.erb
> +        <h3 class="peer-review-full-name">
have to remove this h3, that's [not valid here](https://stackoverflow.com/a/8005953/12432170). we can add a class to the legend if needed.

2020-12-03 16:59 UTC, rshipp commented on app/views/peer_review_submissions/new.html.erb
> -          <legend><%= question.text %></legend>
need to put this fieldset and legend back, this is an accessibility requirement. it's ok to have a fieldset within a fieldset, if you want to have it grouped by both user and question.

2020-12-03 17:00 UTC, rshipp commented on app/views/peer_review_submissions/new.html.erb
> +          <h5 id="<%= input_name %>" class="peer-review-question">
be sure to remove this heading once this is back to a legend

2020-12-03 17:01 UTC, rshipp requested changes
see comments

2020-12-03 17:13 UTC, rshipp commented on app/views/peer_review_submissions/new.html.erb
> +          <h5 id="<%= input_name %>" class="peer-review-question">
this aria-labelledby seems wrong too, I don't think that should be on a div? we already have a label for the input

2020-12-03 17:35 UTC, sadleb commented on app/views/peer_review_submissions/new.html.erb
> +          <h5 id="<%= input_name %>" class="peer-review-question">
Hmm, I was just going off what I found in the FormAssembly CSS. It seems like the`role="radiogroup" aria-labelledby=<the_id>` where the text for the group has the ID is an alternate approach to accessibility: https://www.w3.org/WAI/tutorials/forms/grouping/#associating-related-controls-with-wai-aria -- but I didn't research it much.

Anyway, I like being consistent with the fact that we use fieldset/legend for the grouping of the user so I'll change this.

2020-12-03 17:35 UTC, sadleb commented on app/views/peer_review_submissions/new.html.erb
> -          <legend><%= question.text %></legend>
See below for more context. I'll put this back.

2020-12-03 17:41 UTC, rshipp commented on app/views/peer_review_submissions/new.html.erb
> +          <h5 id="<%= input_name %>" class="peer-review-question">
as a general rule, semantic elements are preferred over the aria alternatives. things like `<a aria-role="button">` are workarounds for when you're constrained on what you can do with the HTML for some reason (e.g. in a legacy codebase where it's easier to add an attribute than change an element and have to fix all your css/js)

2020-12-03 18:25 UTC, jessouyangbraven reviewed
Just the question on `shared/variables` inline. Otherwise, @rshipp's review's really thorough and I'll defer to him on this PR.

2020-12-03 18:25 UTC, jessouyangbraven commented on app/assets/stylesheets/layouts/lti_canvas.scss
> +  height: 100vh; // Height of iframe viewport layout, not the actual screen
Should this be a `$contaniner-...` variable in `shared/variables`?

2020-12-03 18:33 UTC, sadleb commented on app/assets/stylesheets/layouts/lti_canvas.scss
> +  height: 100vh; // Height of iframe viewport layout, not the actual screen
I don't think so. It's not a "style" that we would use in multiple places and want them all changed in one go if we decide to change the value. This is just explicitly setting the height of this container to 100% of the screen dimensions available to it inside the iframe. This is specific to this layout where we show everything in an iframe. When we're not in an iframe, the `html, body` are already set to %100 which effectively does the same thing. See here for more detail: https://stackoverflow.com/a/27804632

2020-12-03 23:15 UTC, sadleb commented on app/assets/stylesheets/peer_review_submissions.scss
> +    text-transform: capitalize;
Yup, I agree. I'll get new screenshots up for you to react to once I finish the changes. I am still using DIN font for the questions which I'm curious to get your thoughts on.

2020-12-03 23:24 UTC, sadleb commented
I've addressed the feedback and updated the screenshots. Re-requested your review @rshipp

2020-12-04 16:35 UTC, rshipp approved these changes

2020-12-04 16:37 UTC, rshipp commented on app/assets/stylesheets/peer_review_submissions.scss
> +    text-transform: capitalize;
Yeah, it might be better with our regular paragraph font. IIRC one of the style guide things was "don't over-use" the headings font. This is a design question and not a a11y one though, so I'm fine with changing it later.

2020-12-04 23:22 UTC, merged