Sync TAs on Salesforce Program to LMS
bebraven/platform pull request #510
Opened 2020-12-15 17:49 UTC by Rowantatai

### Background:
**User Story:**  We need a further automated process for TA onboarding to the Portal/Zoom/Slack
**Context:** We've added TAs into Salesforce to automate the onboarding experience and manage this group of program participants similar to our LCs, CPs, & Fellows.
**Related Asana Tasks:** https://app.asana.com/0/1185361437008970/1199529205874053/f

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [x] I have added neccessary labels
- [? ] My PR title follows the convention in the guide
- [x] I have assigned myself to the PR
- [x] I have requested reviews from team members
- [x] I have created a task for reviewers on PM tool
- [?] All new and existing tests passed.

2020-12-15 18:04 UTC, skaex commented on lib/sync_to_lms.rb
>      elsif role == :'Leadership Coach'
You actually don't need to change this. We don't use this file anymore.

2020-12-15 19:57 UTC, Rowantatai commented on app/services/sync_portal_enrollment_for_account.rb
> +    section.exist? && user.exist?
This is the start of where the tests are failing

2020-12-15 20:33 UTC, rshipp commented on app/services/sync_portal_enrollment_for_account.rb
> +    section.exist? && user.exist?
`find_by` returns `nil` if it can't find anything, so i think `section.exist?` will fail. https://apidock.com/rails/ActiveRecord/FinderMethods/find_by

I think you want something like `section && user` instead.

2020-12-15 23:41 UTC, sadleb requested changes

2020-12-15 23:41 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +  attr_reader :portal_user, :sf_participant, :sf_program
We had a bigger discussion about these attribute readers before and decided not to use them instead of the instances directly generally. Not worth refactoring this class at the moment though, so since you are using the `user` attribute in the code, you should put this back as an `attr_reader`

2020-12-15 23:41 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if can_edit_role?
What does this do? If there is no section, now this will fail? Should it be 
```
user.remove_role enrollment.type, section if section and can_edit_role?
```
?

2020-12-15 23:41 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if can_edit_role?
Also, is this going to break the nightly SyncToLMS? What user does the rake task run as? If they aren't an admin I think it will fail.

2020-12-15 23:41 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.add_role role, section if can_edit_role?
Ditto on being able to run a nightly Sync To LMS rake task. Will this work as whatever use the task runs as?

2020-12-15 23:41 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +  end
Oh, now that I got to this code my comment above needs to change slightly. This won't work. `section` isn't defined here. Also, `can_edit_role?` makes me think you're checking Pundit's authorization policies but you're not. You're just making sure these two variables are defined. Even if this was going to work, it should be named something more like `user_has_section?`

2020-12-16 14:54 UTC, Rowantatai commented on app/services/sync_portal_enrollment_for_account.rb
> +  attr_reader :portal_user, :sf_participant, :sf_program
A user method is already defined though

2020-12-16 14:56 UTC, Rowantatai commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if can_edit_role?
I know nothing about a SyncToLMS rake task nor do I see it in the Heroku Scheduler

2020-12-16 15:11 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if user_can_edit_role?(section)
What happens if you just leave the old code in place? I still think `user_can_edit_role?` is very confusing and I don't understand what this is doing.

2020-12-16 15:11 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +  attr_reader :portal_user, :sf_participant, :sf_program
gotcha

2020-12-16 15:12 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.add_role role, section if user_can_edit_role?(section)
The section was already passed in. Why do we need to check if it exists? What happens if you just leave the old code in place?

2020-12-16 15:13 UTC, rshipp commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if can_edit_role?
@sadleb can_edit_role already checks the section. and to my knowledge rake tasks don't run as a user.

2020-12-16 15:20 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if user_can_edit_role?(section)
Cc @rshipp

2020-12-17 16:56 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if user_can_edit_role?(section)
From Slack for prosperity:
-----
Rowan Tatai Yeah, I don’t think it’ll break existing logic. But to your question around the user_can_edit_role? method, it is important bc there’s a chance the user or section will not exist so its reasonable to check first. Does that answer suffice?
11:55 AM
Brian The section not existing was already handled by the old code.
Are you saying that with this change, the user may not exist where before we only ran this for users that did exist? How will the TA user be created and how will this be called? If the user doesn't exist, does the Sync do anything or should it just short-circuit out in the `run` with a warning log about the user not existing? (edited)

2020-12-17 17:08 UTC, rshipp commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if user_can_edit_role?(section)
i'm not following. the old code only checked section, the new code checks section and user. if you look in `initialize` above, the user is no longer guaranteed to exist, so it makes sense to check both here. if there's no user, removing its role doesn't make any sense, so this code seems fine to me.

2020-12-17 17:09 UTC, rshipp commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.add_role role, section if user_can_edit_role?(section)
the section being passed in doesn't mean it exists, it could be `nil`

2020-12-17 17:31 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.add_role role, section if user_can_edit_role?(section)
It's created in `sync_enrollment` and passed into `enroll_user`.

2020-12-17 17:32 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if user_can_edit_role?(section)
That's my main question. Why are we running this at all for a user that doesn't exist. I don't understand the bigger picture here that makes us want to sync enrollments for a non-existing user @Rowantatai

2020-12-17 17:58 UTC, Rowantatai commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if user_can_edit_role?(section)
So, here's some additional background context to explain the core of this change:
- Regions needed TAs to have periscope dashboards set in advance. 
- TA dashboards are created using mycohortinfo data.
- Mycohortinfo breaks if the TA isn't on canvas. So, I was asking about a way we can have TAs in canvas while still allowing them to create a platform account. 

NEW information discovered: Mycohortinfo doesn't appear to break if we just upload the CSV with the TAs name exactly matching that on salesforce (and match on the name on the Periscope side.)

2020-12-17 18:34 UTC, sadleb commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.remove_role enrollment.type, section if user_can_edit_role?(section)
I would add this context to `user_can_edit_role?` as a comment then @Rowantatai - after that, I'm good with the rest.

2020-12-17 20:15 UTC, Rowantatai commented on app/services/sync_portal_enrollment_for_account.rb
> +    user.add_role role, section if can_edit_role?
Ditto on [Ryan's comment](https://github.com/bebraven/platform/pull/510#discussion_r544378607)

2020-12-17 21:44 UTC, sadleb approved these changes

2020-12-17 21:46 UTC, merged