RFC: Fix UX from Account Creation Process
bebraven/platform pull request #556
Opened 2021-01-14 18:29 UTC by Rowantatai

Enhance UX when people use the account creation link
- Support 18 character IDs in SF APIs so that all platform users are notified to login instead AND direct them to a path that will ultimately get them back to canvas
- Inform end user signing up with any validation failures (ex: password mismatch etc)

### Motivation and Context

Reduce the numbers of "Something went wrong" or "The change you wanted was rejected" experiences

![Screen Shot 2021-01-13 at 10 51 27 AM](https://user-images.githubusercontent.com/20307391/104632312-805d0000-566b-11eb-83d5-366abc0fa5ed.png)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [x] I have added neccessary labels
- [x] My PR title follows the convention in the guide
- [x] I have assigned myself to the PR
- [x] I have requested reviews from team members
- [x] I have created a task for reviewers on PM tool
- [x] All new and existing tests passed.

2021-01-14 18:34 UTC, Rowantatai commented on app/controllers/users/registrations_controller.rb
> +    User.where('salesforce_id LIKE ?', "#{salesforce_id}%").first
@hcli-work "The API tools will accept the 15 character IDs as input but it will always provide you the 18 character ID when you export data. **It is a Salesforce best practice to use 18 character IDs in APIs, formulas or as reference due to its case insensitive nature.**"

2021-01-14 18:39 UTC, Rowantatai commented on app/controllers/users/registrations_controller.rb
> +    flash[:notice] = e.message
TODO: Find a nicer way to output this information

2021-01-14 19:04 UTC, hcli-work commented on app/controllers/users/registrations_controller.rb
> +    User.where('salesforce_id LIKE ?', "#{salesforce_id}%").first
this makes me uneasy because the solution is wed to this 15/18 character trait of Salesforce but the query is much more generic than that.  how about in the definition of `salesforce_id` you stripped it of leading/trailing whitespace and ensured it was either 15 or 18 characters. if it's not, then raise an error. this feels important because it's a user provided value.

next, can we implement a User validation check that the salesforce_id we save in the database is always 18 characters after stripping of whitespace? moreover, how about also implementing a uniqueness constraint on that column?

2021-01-14 19:11 UTC, hcli-work requested changes

2021-01-14 19:11 UTC, hcli-work commented on app/controllers/users/registrations_controller.rb
> +    flash[:notice] = e.message
putting a todo in the comments isn't going to remind anyone to remember to do it. maybe make an Asana task in our backlog instead?

2021-01-15 15:46 UTC, sadleb commented on app/controllers/users/registrations_controller.rb
> +    flash[:notice] = e.message
I need more info on how to reproduce the issue you're trying to solve before I can weigh in here. The Salesforce ID here comes from API so it should always be the same. How are we getting different formats?

Once I understand that, I would recommend that you look for the specific error we know about and flash a human readable message about the issue. E.g. "You already have an account, please login." if we know that the reason is b/c they are trying to sign-up a second time.

2021-01-15 15:56 UTC, sadleb commented on app/controllers/users/registrations_controller.rb
> +    redirect_to new_user_registration_path(u: sign_up_params['salesforce_id'])
This doesn't make sense to me. The `create` action is called when the `new_user_registration_path` form is submitted. The only thing they type in that form is their password. Is this to handle the situation of a password mismatch? Or to handle some Salesforce ID issue? If we're just trying to handle password mismatches, we should explicitly look for that and only redirect in that situation. Otherwise, we're going to mask any number of issues that could go wrong and never get the exceptions sent to Honeycomb/Sentry/logs to be able to debug.

2021-01-19 23:22 UTC, Rowantatai commented on app/controllers/users/registrations_controller.rb
> +    flash[:notice] = e.message
@sadleb It seems like this is happening when we're manually concatenating it (at the minimum). Here's a sample:
15 chars (i.e., account creation link on salesforce)
- Link: https://platform.bebraven.org/users/sign_up?u=0031J00001dGfqK
- Current Behaviour: "YOU'VE ALREADY SIGNED UP!"

18 chars (i.e., manual concatenation)
- Link: https://platform.bebraven.org/users/sign_up?u=0031J00001dGfqKQAS
- Current Behaviour: "CREATE ACCOUNT" then "The change you wanted was rejected" Error (bc email is already in use)

2021-01-19 23:34 UTC, Rowantatai commented on app/controllers/users/registrations_controller.rb
> +    redirect_to new_user_registration_path(u: sign_up_params['salesforce_id'])
Handle other situations. lol the thesis of this PR is to enhance the UX account creation process...but now I see why it may be confusing. Thanks for flagging the confusion. 

This is intended to handle the situation of a password mismatch, password already created, Password is too short, and email already signed up (this should direct to "you've already signed up" though). All of the `ActiveRecord::RecordInvalid` I've encountered were around the ones mentioned above. What are some other issues you suspect will get masked from this?

2021-02-18 18:30 UTC, rshipp commented on app/controllers/users/registrations_controller.rb
> +    flash[:notice] = e.message
Oh interesting, this is something I ran into when I was doing salesforce stuff too, but I didn't have a clue what was going on. @sadleb per @Rowantatai's comment above about the Salesforce best practices, can we change the autogenerated sign_up link to use the full, 18 character IDs? That will simplify validation/querying a lot on our end.

2021-03-24 01:46 UTC, sadleb commented on app/controllers/users/registrations_controller.rb
> +    flash[:notice] = e.message
If there is some Salesforce API call we can make to take a 15 char ID and get the 18 char ID back, I think we should put a database validation in place and only store the
18 char IDs. It would require us to fix the places where a 15 char ID is currently coming through though. If we can change the auto-generated links, that would be the first place. The second that I can think of is the admin dashboard that allows you to manually change an ID.

2021-03-24 01:54 UTC, sadleb commented on app/controllers/users/registrations_controller.rb
> +    redirect_to new_user_registration_path(u: sign_up_params['salesforce_id'])
Currently, I bet those are the only situations that would cause this. But someone could refactor the code and mess things up and forget to set their first name or something in certain situations. That would lead to an error happening of when they were manually testing and happened to hit that situation but be masked in prod of manual testing didn’t catch it.

2021-03-24 01:59 UTC, sadleb commented on app/controllers/users/registrations_controller.rb
> +    redirect_to new_user_registration_path(u: sign_up_params['salesforce_id'])
Btw, we’ve already put in some fixes in a slightly different way for some of this stuff (not the SF ID character length issue tho) in Highlander. So we shouldn’t spend much time on this and instead figure out what is left of the things that cause all this noise which still need to be fixed in Highlander.

2021-05-05 15:13 UTC, rshipp commented
All existing (Highlander Platform) users are migrated to use the 18-char IDs, and 18-char IDs are enforced (in Highlander) as of #685. Leaving this PR open just in case until Highlander is merged to `staging`.

2021-07-19 23:24 UTC, sadleb commented
I think most of this is implemented elsewhere at this point. We should re-open narrower user stories / PRs as we run into pain points

2021-07-19 23:24 UTC, closed without merging