Add AttendanceEventSubmission
bebraven/platform pull request #557
Opened 2021-01-14 23:17 UTC by jessouyangbraven

### Description

**Task**: https://app.asana.com/0/1174274412967132/1197571375872706

This PR introduces attendance for the LC Playbook course.

### Motivation and Context

### Screenshots (if appropriate):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2021-01-14 23:27 UTC, jessouyangbraven commented on app/models/attendance_event_submission.rb
> +  end
RFC: @sadleb brought this up when I implemented `FellowEvaluationSubmission`. At the time, I was pattern matching on existing submissions and not thinking ahead to this attendance stuff.

Should we have an `AttendanceEventSubmission` per fellow being reviewed by the LC, or stay consistent with existing submission data models and have `AttendanceEventSubmissionAnswer` (or `Status` or whatever makes sense to call it), one for each user, that all `belong_to` the `Submission`?

There are two categories of `Submissions`:
1. Submissions that involve you filling out the same fields for a list of `target_user`s: `{PeerReview, FellowEvaluation, AttendanceEvent}Submissions` fall into this category

2. Submissions that involve you filling out a bunch of a stuff for a single logical "form", `{Waivers, PreAcceleratorSurvey, PostAcceleratorySurvey, Project, Survey}Submission` fall into this category.

2021-01-14 23:28 UTC, jessouyangbraven commented on app/models/attendance_event_submission.rb
> +  end
We don't store anything for waivers, pre/post accelerator surveys. So I think the question I'm trying to ask if whether the data model for category (1) should be different for `Project` and `SurveySubmissions`.

2021-01-14 23:33 UTC, jessouyangbraven commented on app/models/attendance_event_submission.rb
> +  end
<img width="1315" alt="Screen Shot 2021-01-14 at 3 32 39 PM" src="https://user-images.githubusercontent.com/62911934/104661617-be631f80-567d-11eb-9c1c-9453632afaf5.png">

2021-01-14 23:33 UTC, jessouyangbraven commented on app/models/attendance_event_submission.rb
> +  end
<img width="1329" alt="Screen Shot 2021-01-14 at 3 32 25 PM" src="https://user-images.githubusercontent.com/62911934/104661658-dc308480-567d-11eb-80b4-d70e3a056531.png">

2021-01-15 18:30 UTC, jessouyangbraven commented on app/models/attendance_event_submission.rb
> +  end
https://app.asana.com/0/inbox/1168520191375327/1199544270990456/1199539421634484

2021-01-15 18:30 UTC, jessouyangbraven commented on app/models/attendance_event_submission.rb
> +  end
https://app.asana.com/0/1174274412967132/1199544270990456

2021-01-20 03:41 UTC, jessouyangbraven commented on app/models/attendance_event_submission.rb
> +  end
We went with keeping things consistent with existing `Submission` and `Answer` models, so having the `for_user_id` on the `submission_answers` table.

2021-01-20 18:33 UTC, rshipp approved these changes

2021-01-20 19:41 UTC, sadleb requested changes

2021-01-20 19:41 UTC, sadleb commented on db/migrate/20210114220410_create_attendance_event_submissions.rb
> +    end
We're missing the timestamps for `created_at` and `updated_at`

2021-01-20 21:07 UTC, sadleb approved these changes
lgtm

2021-01-20 23:00 UTC, merged