Accelerator Surveys - launch in iframe parent, link back to course when done
bebraven/platform pull request #559
Opened 2021-01-19 19:42 UTC by rshipp

### Description

### Motivation and Context

Task: https://app.asana.com/0/1174274412967132/1199539421634497/f

### Screenshots (if appropriate):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2021-01-19 20:49 UTC, rshipp commented on app/controllers/waiver_submissions_controller.rb
> +  # GET /waiver_submissions/launch
just updating these comments to the correct urls

2021-01-19 20:55 UTC, rshipp commented on spec/policies/accelerator_survey_submission_policy_spec.rb
> +  permissions :launch? do
copied from `new?`

2021-01-20 14:24 UTC, sadleb commented on app/controllers/accelerator_survey_submissions_controller.rb
> +  # This way, it's just a static endpoint for any course to launch the waivers for that course pulling the
typo: waivers == surveys

2021-01-20 14:26 UTC, sadleb commented on app/controllers/accelerator_survey_submissions_controller.rb
> +    authorize instance_variable
Is `instance_variable` actually set? I don't think `DryCrud` knows about the launch action, so this may be nil?

2021-01-20 14:32 UTC, sadleb approved these changes
Couple small nits but not merge blocking if it's been tested and works.

2021-01-20 17:02 UTC, jessouyangbraven approved these changes

2021-01-20 17:37 UTC, rshipp commented on app/controllers/accelerator_survey_submissions_controller.rb
> +    authorize instance_variable
ironically, `instance_variable` is a method, not a variable, so the concerns don't need to know about this action.

2021-01-21 17:14 UTC, sadleb requested changes
See the bug comment regarding the redirect.

2021-01-21 17:14 UTC, sadleb commented on app/controllers/accelerator_survey_submissions_controller.rb
> +    redirect_to completed_submissions_path if previous_submission
Ran into a bug with waivers that needs to be applied here too. See: https://github.com/bebraven/platform/pull/566

2021-01-21 17:44 UTC, rshipp commented on app/controllers/accelerator_survey_submissions_controller.rb
> +    redirect_to completed_submissions_path if previous_submission
i didn't realize it was broken with waivers, but i've already fixed it here.

2021-01-21 18:26 UTC, sadleb commented on app/controllers/accelerator_survey_submissions_controller.rb
> +    redirect_to completed_submissions_path if previous_submission
Oh, whoops. Didn’t realize it was a method here and not just the normal rails helper

2021-01-21 18:26 UTC, sadleb approved these changes

2021-01-21 20:05 UTC, merged