First pass at adding LC taking attendance controller logic
bebraven/platform pull request #564
Opened 2021-01-20 22:46 UTC by jessouyangbraven

### Description

### Motivation and Context

### Screenshots (if appropriate):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2021-01-22 22:36 UTC, jessouyangbraven reviewed
I left some questions/comments inline, nothing merge-blocking from me, though.

2021-01-22 22:36 UTC, jessouyangbraven commented on app/assets/stylesheets/layouts/application.scss
> +}
I'll defer to @sadleb on the CSS, but should this go in an attendance-specific file rather than at the top-level application one?

2021-01-22 22:36 UTC, jessouyangbraven commented on app/helpers/application_helper.rb
> +    end
nit: `condition == true ? 'selected' : ''`

2021-01-22 22:36 UTC, jessouyangbraven commented on app/helpers/application_helper.rb
> +    end
nit: ditto

2021-01-22 22:36 UTC, jessouyangbraven commented on app/views/attendance_event_submissions/_form.html.erb
> +  <div class="col-sm-12">
Should we take out this `<div>`? It makes everything really smooshed to the center.

2021-01-22 22:36 UTC, jessouyangbraven commented on app/views/attendance_event_submissions/_form.html.erb
> +  <div class="col-sm-6">
Ditto this one. I think we usually do this for the admin pages on platformweb not for things in the LTI launch/Canvas view?

2021-01-22 22:42 UTC, sadleb commented on app/assets/stylesheets/layouts/application.scss
> +}
Yeah, this feels very specific to this form so it shouldn’t apply to all pages in the app based on the wiki for how to structure CSS.

2021-01-22 22:44 UTC, rshipp commented on app/views/attendance_event_submissions/_form.html.erb
> +  <div class="col-sm-12">
😓 it didn't for me, can you screenshot what you're seeing? i don't understand the bootstrap grid stuff but i thought i had it working

2021-01-22 22:45 UTC, rshipp commented on app/views/attendance_event_submissions/_form.html.erb
> +  <div class="col-sm-12">
maybe it's a difference between iframed on canvas and just viewing the page, I only tested without canvas

2021-01-22 22:48 UTC, rshipp commented on app/helpers/application_helper.rb
> +    end
oh, really? i thought people didn't like ternary, so i changed it to this to be "more readable". personally I'm fine with switching it back though.

2021-01-25 20:30 UTC, sadleb commented on app/helpers/application_helper.rb
> +    end
My personal opinion is that ternary is fine for very basic stuff, like this. I personally don't like ternary if it's more than one line or even a really long line.

2021-01-25 21:29 UTC, rshipp commented on app/views/attendance_event_submissions/_form.html.erb
> +  <div class="col-sm-12">
I removed the divs but I can't tell that it made any difference, so let me know if something's still broken

2021-01-25 21:31 UTC, rshipp approved these changes

2021-01-25 23:26 UTC, sadleb requested changes

2021-01-25 23:26 UTC, sadleb commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w( attendance_event_submissions.css )
Only top-level layout manifests should be here. The individual files that go into the combined layout CSS are added with a `require` in the layout CSS. See the application or content_editor layout CSS for an example

2021-01-26 13:29 UTC, sadleb commented on app/views/attendance_event_submissions/_form.html.erb
> +  <div class="col-sm-12">
I took a quick pass at using the Bootstrap grid stuff to make it look slightly better. See the updated screenshots in the PR description.

2021-01-26 13:30 UTC, sadleb approved these changes

2021-01-26 13:30 UTC, merged