Redirect non admin users to the portal
bebraven/platform pull request #565
Opened 2021-01-21 16:02 UTC by Rowantatai

### Description

While authenticated, our platform.bebraven.org serves admins only. When a non-admin authenticated user stumbles upon platform, they will be redirected to canvas. 

### Motivation and Context

Currently, they're being directed to "We're sorry, but something went wrong" error page. In the logs, it translates to `Pundit::NotAuthorizedError (not allowed to index? this Symbol):`

### Test Plan
_Case 1 - non-admin user_
1. Login to platform
2. Visit platform.bebraven.org
Outcome: redirects to canvas

_Case 2 - admin user_
1. Login to platform
2. Visit platform.bebraven.org
Outcome: stays on platform

### Checklist

- [x] My code follows the code style of this project.
- [x] I have added neccessary labels
- [x] My PR title follows the convention in the guide
- [x] I have assigned myself to the PR
- [x] I have requested reviews from team members
- [x] I have created a task for reviewers on PM tool
- [?] All new and existing tests passed.

2021-01-21 16:56 UTC, Rowantatai commented on spec/controllers/custom_content_versions_controller_spec.rb
> +      xit 'raises a not-authorized error' do
I tried to get redirection working instead of raising the error but haven't been successful yet

2021-01-21 17:37 UTC, sadleb requested changes

2021-01-21 17:37 UTC, sadleb commented on app/controllers/application_controller.rb
> +  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
I'm a bit worried about this. It might be fine in non-Highlander since there is nothing other than the CAS SSO stuff on platform for non-admins. But in Highlander, this is likely going to get us in trouble when the authorization failed for some other reason and we end up in an infinite loop of sorts. Also, it will mask the actual errors from our logs and Honeycomb to be able to troubleshoot.

How about we just do this sort of thing in the `home_controller`? I think we've probably already mostly solved the issue by switching the `new_user_session_path` to `cas_login_url`, but having the redirect only on the home controller feels like a safer fallback for whatever root cause we may have missed. E.g. does password reset end up causing this and we need to switch a URL there as well?

When you implement the redirect in the `home_controller` I would explicitly check if the user has an admin role and redirect to Canvas if not instead of relying on an exception.

2021-01-21 19:09 UTC, hcli-work requested changes

2021-01-21 19:09 UTC, hcli-work commented on app/controllers/application_controller.rb
> +  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
+1

2021-01-21 19:09 UTC, hcli-work commented on spec/controllers/custom_content_versions_controller_spec.rb
> +      xit 'raises a not-authorized error' do
commenting out a test that doesn't work feels like not the right step.

2021-01-22 13:01 UTC, sadleb commented on app/controllers/application_controller.rb
> +  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
One more potential root cause I just remembered. I think log-out can cause this b/c it log's you out to the platform log-in page but loses the `service` URL that tells login to bring you to Canvas. The above solution with the `home_controller` should fix that scenario, but in a hacky way. The proper fix is probably to preserve the `service` URL. This wasn't as much of a problem before b/c the Join server would * mostly * be able to figure out where you should go and redirect you but now with it largely out of the picture everyone who logs out and back in is perhaps ending up at the "something went wrong screen"

2021-01-26 16:32 UTC, Rowantatai commented on spec/controllers/custom_content_versions_controller_spec.rb
> +      xit 'raises a not-authorized error' do
Agreed. The decision to update the test depended on alignment of the changes. Not necessary anymore.

2021-01-26 17:22 UTC, Rowantatai commented on app/controllers/application_controller.rb
> +  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
I moved the rescue from the application controller and instead ensured the user is an admin in the home controller, as requested. I created a backlog task to preserve the service url [here].(https://app.asana.com/0/1179330853755533/1199679486201904/f)

2021-01-27 01:33 UTC, sadleb approved these changes
I don’t know where `:canvas` is defined in the redirect, but assuming it is and it’s the correct URL, lgtm!

2021-01-27 01:37 UTC, sadleb commented
> I don’t know where `:canvas` is defined in the redirect, but assuming it is and it’s the correct URL, lgtm!

Wait, actually, do you need to do redirect `and return` ? Generally, I think the rest of the code executes after calling redirect so does that mean the Not Authorized exceptions are being thrown but it still redirects? I don’t know how it works in a before action, but assuming you tested this and it works, still lgtm

2021-01-27 14:45 UTC, hcli-work approved these changes
when this goes live, make sure to test for both Booster and Accel.

2021-01-27 20:51 UTC, merged