Add controller that creates a new page in platform that'll allow stud…
bebraven/platform pull request #581
Opened 2021-02-08 15:49 UTC by a-willis

Project Task:
https://app.asana.com/0/1179330853755533/1199391832901943/f

Test Plan:
http://platformweb:3020/users/portal_password/5823/edit

2021-02-08 20:13 UTC, hcli-work commented
Lexi, I'm a little confused here. I thought you were creating a whole new controller instead of mucking around with Devise anymore. Did I misunderstand that?

2021-02-11 19:51 UTC, hcli-work requested changes

2021-02-11 19:51 UTC, hcli-work commented on .vscode/settings.json
> +{
you'll need to add `.vscode` to your `.gitignore` file so that git ignores these config files for your editor

2021-02-11 19:51 UTC, hcli-work commented on app/controllers/users/passwords_controller.rb
> +  skip_before_action :require_no_authentication, :only => [:edit, :update]
should this be here? it feels like if we are adding a new controller, we shouldn't have to touch this existing one.

2021-02-11 19:51 UTC, hcli-work commented on app/controllers/users/passwords_controller.rb
> +   # GET /resource/password/edit?reset_password_token=abcdef
similarly, let's revert this so it doesn't conflate whitespace issues with the meat of this PR

2021-02-11 19:51 UTC, hcli-work commented on app/controllers/users/portal_password_controller.rb
> +class Users::PortalPasswordController < UsersController
can you explain why there's a need to inherit from `UsersController` instead of `ApplicationController`?

2021-02-11 19:51 UTC, hcli-work commented on app/controllers/users/portal_password_controller.rb
> +  # GET	/users/portal_password/5823/edit
perhaps we shouldn't allow passing in of ids at all. it feels like it would leave opportunity for someone to do something bad like alter another's password. can we just grab the id based on who is logged in?

typically, the `ApplicationController` will have a method on it called `current_user`. we can just use `current_user.id` which would close up the security vulnerability and make the `find_user` method and instance variable `@user` unnecessary.

2021-03-31 22:40 UTC, sadleb commented
For Highlander, this is related to this task: https://app.asana.com/0/1174274412967132/1199950461423843 -> if we implement a page that allows folks to change their email, we should also allow them to change their password from there (while logged in, which is different from password reset used when you can’t login in the first place).

2021-07-19 23:28 UTC, sadleb commented
Closing bc this got deprioritized in favor of folks using the password reset flow after logging out in order to reset their password. The more common user sorry is that someone can’t login and needs to reset their password. We should implement a way for them to change it while they’re logged in at some point, but that could be months or years from now.

2021-07-19 23:28 UTC, closed without merging