Discord bot: quick fixes
bebraven/platform pull request #749
Opened 2021-06-21 19:22 UTC by rshipp

### Description

Followup to fix/refactor some small issues, including Salesforce changes introduced in #743.

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2021-06-21 21:45 UTC, sadleb requested changes

2021-06-21 21:45 UTC, sadleb commented on lib/salesforce_api.rb
> +                             :cohort, :cohort_schedule, :cohort_id,
Do you have to add this at the end unless you go find all calls to `SFParticipant.new` and re-order the params?

2021-06-21 22:18 UTC, rshipp commented on lib/salesforce_api.rb
> +                             :cohort, :cohort_schedule, :cohort_id,
Yes, but we don't use anything this far down the list except in find_participant below

2021-06-23 20:11 UTC, rshipp commented
merging bc we need this for test meeting tomorrow

2021-06-23 20:11 UTC, merged