Add confirm button, change confirm failed language
bebraven/platform pull request #767
Opened 2021-07-13 16:12 UTC by rshipp

### Description

Make people click a button to confirm their email, and stop allowing confirmation by GET request. Change the language on the confirmation error page to make it clearer that if the user has already confirmed, they should just log in instead.

### Motivation and Context

Tasks:

* Confirm button: https://app.asana.com/0/1174274412967132/1200448671778587/f
* Error page changes: https://app.asana.com/0/1174274412967132/1200448671778585/f

### Screenshots (if appropriate):

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

2021-07-13 16:18 UTC, Javier99620 requested changes
-

2021-07-15 14:27 UTC, sadleb commented on app/views/devise/confirmations/show.html.erb
> +        <%= f.hidden_field :confirmation_token, value: params[:confirmation_token] %>
I assume you tested that this works? Aka that the token comes through nested so that `params.dig(:user, :confirmation_token)` is that value posted here.

2021-07-15 14:29 UTC, sadleb commented on app/views/devise/confirmations/show_resend.html.erb
> +    <p>If you have <strong>already confirmed your account</strong>, try <%= link_to 'logging in', cas_login_path %> instead.</p>
I forget, did we make the generic `cas_login_path` work better or should we be trying to pass in a `service` param?

2021-07-15 14:31 UTC, sadleb approved these changes
No merge blocking comments assuming that you actually tested that confirmation works.

2021-07-15 15:59 UTC, rshipp commented on app/views/devise/confirmations/show.html.erb
> +        <%= f.hidden_field :confirmation_token, value: params[:confirmation_token] %>
Not sure if i understand, but the `hidden_field :confirmation_token` inside a `form_with(model: User` will send `user[confirmation_token]`. the `params[:confirmation_token]` reads the value from the `?confirmation_token=` url param, it doesn't set the name sent by the form.

2021-07-15 15:59 UTC, rshipp commented on app/views/devise/confirmations/show_resend.html.erb
> +    <p>If you have <strong>already confirmed your account</strong>, try <%= link_to 'logging in', cas_login_path %> instead.</p>
don't remember, I didn't touch anything there

2021-07-15 16:39 UTC, sadleb commented on app/views/devise/confirmations/show_resend.html.erb
> +    <p>If you have <strong>already confirmed your account</strong>, try <%= link_to 'logging in', cas_login_path %> instead.</p>
It's fine to leave it like it was b/c its outside the scope of this PR, but it looks like in registrations_controller we use `cas_login_path(service: CanvasConstants::CANVAS_URL)` b/c Canvas is our main "service" that someone registering would expect to be sent to. It may be better to do the same here just in case the after login stuff doesn't properly redirect to Canvas instead of the home controller.

2021-07-15 16:59 UTC, rshipp commented on app/views/devise/confirmations/show_resend.html.erb
> +    <p>If you have <strong>already confirmed your account</strong>, try <%= link_to 'logging in', cas_login_path %> instead.</p>
changed it. another reason to get rid of cas 🙃

2021-07-16 15:58 UTC, merged