Updated waiver policy so only fellows can launch waivers
bebraven/platform pull request #876
Opened 2021-10-14 20:23 UTC by elenabaurkot

### Description
Updated the waiver policy so that in order to launch waivers the user must be a student enrolled in the course they are trying to open the waiver for. 

### Motivation and Context
Previously, if an LC opened a waiver, it seemed to be working until they tried to submit and received an error message because they aren't a student and we can't create a grade for them. We want to prevent LCs/TAs from opening waivers all together.

Asana task: https://app.asana.com/0/1174274412967132/1200882227720691/f 

### Screenshots (if appropriate):
From the screen below, the button to load for waivers should only work for fellows
<img width="707" alt="Screen Shot 2021-10-14 at 9 38 38 AM" src="https://user-images.githubusercontent.com/30561514/137389897-ae5aae32-b5c7-428f-85be-26cf27baf086.png">

When a TA/LC clicks the button to load waivers they receive this error message:
<img width="677" alt="Screen Shot 2021-10-14 at 9 38 49 AM" src="https://user-images.githubusercontent.com/30561514/137389657-a4dc91e8-88a9-4ae4-a37c-46cf29aa02c2.png">

When a fellow clicks the button to load waivers they should be taken to another button that says "click here to get started"
<img width="695" alt="Screen Shot 2021-10-14 at 9 39 28 AM" src="https://user-images.githubusercontent.com/30561514/137389827-0194e4e9-b908-4748-9b0e-876ac44ba962.png">

### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-10-14 20:38 UTC, rshipp requested changes
two comments, the rest looks good

2021-10-14 20:38 UTC, rshipp commented on app/policies/waiver_submission_policy.rb
> +      courseSections = user.sections.select do |section|
nit: can you use `snake_case` for these variables instead of `babyCamelCase`? we try to keep snake in Rails code and camel in our JavaScript.

2021-10-14 20:38 UTC, rshipp commented on app/policies/waiver_submission_policy.rb
>      !!user
this line doesn't do anything right now, i think you want
```suggestion
    return false if user.nil?
```
The `!!user` with no return only works if it's the last line in the function and you take advantage of Ruby's implicit return.

2021-10-14 20:59 UTC, elenabaurkot commented on app/policies/waiver_submission_policy.rb
> +      courseSections = user.sections.select do |section|
For sure, just made the updates!

2021-10-14 22:03 UTC, sadleb commented on app/policies/waiver_submission_policy.rb
> +      courseId = record.id
I think it would be cleaner and more consistent if we create an `initialize` method and set a `@course` instance variable. See `project_submission_policy.rb` for an example of how we do this sort of thing elsewhere.

Also, parroting Ryan's comment about snake_case vs babyCamelCase for `courseId`

2021-10-14 22:04 UTC, sadleb commented on app/policies/waiver_submission_policy.rb
> +        return true if user.has_role? "StudentEnrollment", section
Can we use the `RoleConstants::STUDENT_ENROLLMENT` constant here?

2021-10-15 14:20 UTC, elenabaurkot commented on app/policies/waiver_submission_policy.rb
>      !!user
Ah okay, got it, just edited that

2021-10-15 14:35 UTC, elenabaurkot commented on app/policies/waiver_submission_policy.rb
> +      courseId = record.id
I updated and added the initialize method, I am not sure if I did this correctly though. I was trying to add the @course and initialize it to record.id, but was receiving an error on the initialize method when I tried that. I changed it to look similar to attendance_event_submission_policy.rb where the @record instance variable is initialized and use that to grab the course after. Let me know if this should be changed @sadleb

2021-10-15 19:48 UTC, merged