Added specs for Discord signup launch
bebraven/platform pull request #927
Opened 2021-11-23 15:07 UTC by elenabaurkot

### Description
Added specs for launch in the Discord signups controller. 

### Motivation and Context
To help keep the Discord Signup code maintainable.

2021-11-23 19:11 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +  let(:discordrb_api_user) { instance_double(Discordrb::API::User) }
I never paid attention to `double` vs `instance_double` but it looks like we should lean towards using `instance_double`s b/c they have a little more reliable behavior: https://www.ombulabs.com/blog/rspec/ruby/spy-vs-double-vs-instance-double.html 

We'll probably want to update our guidance somwhere if we all agree to that and maybe do a mass find/replace at some point b/c currently we're arbitrarily choosing one vs the other.

2021-11-23 19:14 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +      let(:params) { { lti_launch_id: lti_launch.id, state: lti_launch.state } }
Doesn't look like this `params` variable is used, right?

2021-11-23 19:18 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +        subject
Maybe we the `subject` in the `before` block elsewhere, but I usually call it in the test itself. For example, would this run the `get launch` twice in the context's below since `it_behaves_like 'renders initial steps'` also calls `subject`? If so, we'd be slowing down the tests unecessarily.

2021-11-23 19:20 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +        subject
Ditto on the comments above about using `subject` in the before. I think this would unnecessarily call it twice.

2021-11-23 19:23 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +  let(:sf_program_struct) { SalesforceAPI.program_to_struct(create(:salesforce_program_record)) }
Is this used?

2021-11-23 19:26 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +      end
Is the `subject` being called here? I'm not sure this test is actually testing anything. If you put the following in here, does it pass?
```
expect(LtiLaunch).to receive(:from_id)
          .with(user, lti_launch.id)
          .and_return(lti_launch)
```

2021-11-23 19:27 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +        user.reload
Ditto on above comments.

2021-11-23 19:31 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +        user.discord_expires_at = "2021-11-20 18:07:10.024855000 +0000"
Is this hardcoded b/c you were trying to get an expiration in the past? If so, you can just do something like `user.discord_expires_at = Time.now.utc - 1.week`

2021-11-23 19:34 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +        let(:discord_user) { { id: "fakeid1", email: nil, verified: false }.to_json }
Should we create a `discord_user` factory similar to how we have factories for Salesforce and Canvas API responses?

2021-11-23 19:34 UTC, rshipp commented on spec/controllers/discord_signups_controller_spec.rb
> +  let(:lti_advantage_api) { double(LtiAdvantageAPI) }
this line can be deleted

2021-11-23 19:35 UTC, rshipp commented on spec/controllers/discord_signups_controller_spec.rb
> +      let(:params) { { lti_launch_id: lti_launch.id, state: lti_launch.state } }
it's used on line 28 in the subject

2021-11-23 19:36 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +              user.remove_role RoleConstants::STUDENT_ENROLLMENT
Don't we get a fresh user for each test? I'm confused why we have to remove the student roles.

2021-11-23 19:38 UTC, rshipp commented on spec/controllers/discord_signups_controller_spec.rb
> +        user.reload
i'd value readability/maintainability over speed in some of these cases. yes, some of them will call the subject twice, but that's pretty negligible if we save a couple lines of code in a few `it` blocks.

2021-11-23 19:40 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +      let(:params) { { lti_launch_id: lti_launch.id, state: lti_launch.state } }
That's the `params` attribute for the `get` method I think. If it was used there it would be `get :launch, params: params` instead.

2021-11-23 19:41 UTC, rshipp commented on spec/controllers/discord_signups_controller_spec.rb
> +        let(:discord_user) { { id: "fakeid1", email: nil, verified: false }.to_json }
I'd lean against doing that, unless we start using it in other places. it's just a small json blob we use in one action in one controller.

2021-11-23 19:42 UTC, rshipp commented on spec/controllers/discord_signups_controller_spec.rb
> +              user.remove_role RoleConstants::STUDENT_ENROLLMENT
i can't use `let` because we modify `user` explicitly in a `before` block in a parent context, and `before` blocks happen after `let`.

2021-11-23 19:44 UTC, rshipp commented on spec/controllers/discord_signups_controller_spec.rb
> +      let(:params) { { lti_launch_id: lti_launch.id, state: lti_launch.state } }
ah that's an oversight then, we should change line 28

2021-11-23 19:55 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +        user.reload
I guess I always think about the `before` block as the test setup and the `it` block is where the test is actually run, so it's less intuitive to me. Then again, that's probably just me and why I haven't fully started to leverage `it { some_matcher }` type tests.

2021-11-23 19:57 UTC, sadleb commented on spec/controllers/discord_signups_controller_spec.rb
> +        let(:discord_user) { { id: "fakeid1", email: nil, verified: false }.to_json }
Sold

2021-11-23 21:07 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +  let(:lti_advantage_api) { double(LtiAdvantageAPI) }
just removed 👍

2021-11-23 21:07 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +  let(:sf_program_struct) { SalesforceAPI.program_to_struct(create(:salesforce_program_record)) }
no, I think I was before, but took it out now

2021-11-23 21:10 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +      let(:params) { { lti_launch_id: lti_launch.id, state: lti_launch.state } }
Removed this on line 44, but I can't figure out what's wrong with line 28

2021-11-23 21:10 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +        subject
Ah I see what you're saying, I updated the subjects all to be inside the 'it' statements now

2021-11-23 21:12 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +      let(:params) { { lti_launch_id: lti_launch.id, state: lti_launch.state } }
I removed this variable on line 44, but I can't figure out what's wrong with line 28

2021-11-23 21:13 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +        subject
Ah I see what you mean, I updated the subject to be in it statements for all of them instead of before

2021-11-23 21:13 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +        subject
👍

2021-11-23 21:13 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +  let(:sf_program_struct) { SalesforceAPI.program_to_struct(create(:salesforce_program_record)) }
No I think I was before, but just removed it

2021-11-23 21:14 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +      end
I see what you're saying that this test isn't actually doing anything, I added in the subject, but am having a hard time getting it to pass after adding this in

2021-11-23 21:14 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +        user.discord_expires_at = "2021-11-20 18:07:10.024855000 +0000"
Yes, just updated to this 👍

2021-11-23 21:14 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +  let(:lti_advantage_api) { double(LtiAdvantageAPI) }
Just removed 👍

2021-11-23 22:39 UTC, elenabaurkot commented on spec/controllers/discord_signups_controller_spec.rb
> +      end
this is working and passing now, much thanks to @rshipp

2021-11-23 22:54 UTC, rshipp requested changes
something weird must have happened during that last `pull --rebase` we did, the commits are all messed up. lmk if it takes you more than a few minutes to figure out and we can fix it in a call tomorrow.

2021-11-24 14:09 UTC, elenabaurkot commented
I think I was able to fix pull --rebase, and it looks OK to me, but let me know if anything looks off

2021-11-24 16:24 UTC, elenabaurkot commented
> looks like it deleted my commit, but the code appears to be in there, so it's probably fine

Whoops, I am not entirely sure I went about fixing this correctly sorry about that @rshipp

2021-11-24 16:27 UTC, rshipp approved these changes

2021-11-24 16:39 UTC, merged